### ISSUE TITLE
[question] What is the correct way of configuring the underlying HttpClient for timeouts?

### ISSUE THREAD

**Issue by javapapo** [rest-assured/rest-assured#1035]
The code below, has deprecation warnings from the http client 
```java
  config = RestAssured.config()
        .httpClient(HttpClientConfig.httpClientConfig()
            .setParam(CoreConnectionPNames.CONNECTION_TIMEOUT, 15000)
            .setParam(CoreConnectionPNames.SO_TIMEOUT, 10000));
```

What is the expected way to - eventually configure the client for timeouts

**Comment by happyheng** [comment]
I have this question, too

**Comment by wangqi81** [comment]
I have the same question. I tried to use custom request config below,
```
RequestConfig requestConfig = RequestConfig.custom()
	.setConnectTimeout(10000)
	.setConnectionRequestTimeout(10000)
	.setSocketTimeout(10000)
	.build();

HttpClientConfig httpClientConfig = HttpClientConfig.httpClientConfig()
		.httpClientFactory(() -> HttpClientBuilder.create().setDefaultRequestConfig(requestConfig).build());

RestAssuredConfig config = RestAssured.config().httpClient(httpClientConfig);

Response response = RestAssured.given().config(config).when().post("https://url/");
```
but I got this Exception:
```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.apache.http.impl.client.InternalHttpClient@64693226' with class 'org.apache.http.impl.client.InternalHttpClient' to class 'org.apache.http.impl.client.AbstractHttpClient'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:418)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:332)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:245)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:616)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1743)
```

**Comment by YogeshBathri** [comment]
any update on the exception mentioned by wangqi81 ?
