### ISSUE TITLE
NoSuchMethodError exception during json schema validation

### ISSUE THREAD

**Issue by asirin48** [rest-assured/rest-assured#1043]
I attempting to add a JSON schema validation to my code. Unfortunately I get an exception (shown below). I am not sure what I am doing wrong... I have put the schema file into the classpath and referenced it in the validator. I have also tried using the fully qualified file name in the validator call . Can you think of why this is happening?

Here is the code snippet:
      response = given()
    		  .when()
    		  .log().all()
    		  .accept(contentType)
    		  .get(endpoint).then()
    		  .log().all()
    		  .body(matchesJsonSchemaInClasspath("issuers-response-schema-v1.json"))
    		  .extract()
    		  .asString();

I am using the following library versions:

    testCompile 'io.rest-assured:rest-assured:3.1.0'

    testCompile 'io.rest-assured:json-schema-validator:3.1.0'

    testCompile 'junit:junit:4.12'

    testCompile 'com.google.code.gson:gson:2.6.2'

    testCompile group:'com.icegreen', name :'greenmail', version :'1.3'

    testCompile group: 'org.apache.commons', name: 'commons-lang3', version: '3.0'

    testCompile 'org.hamcrest:hamcrest-core:1.3'

    testCompile 'org.hamcrest:hamcrest-library:1.3'

Rerun com.mycode.server.api.v1.IssuersEndpointTests com.mycode.server.api.v1.IssuersEndpointTests getAllIssuers(com.mycode.server.api.v1.IssuersEndpointTests) java.lang.NoSuchMethodError: com.google.common.base.Platform.precomputeCharMatcher(Lcom/google/common/base/CharMatcher;)Lcom/google/common/base/CharMatcher; at com.google.common.base.CharMatcher.precomputed(CharMatcher.java:765) at com.github.fge.jsonschema.core.util.URIUtils.<clinit>(URIUtils.java:65) at com.github.fge.jsonschema.core.load.configuration.URIDownloadersRegistry.<init>(URIDownloadersRegistry.java:74) at com.github.fge.jsonschema.core.load.configuration.LoadingConfigurationBuilder.<init>(LoadingConfigurationBuilder.java:76) at com.github.fge.jsonschema.core.load.configuration.LoadingConfiguration.byDefault(LoadingConfiguration.java:151) at com.github.fge.jsonschema.main.JsonSchemaFactoryBuilder.<init>(JsonSchemaFactoryBuilder.java:67) at com.github.fge.jsonschema.main.JsonSchemaFactory.newBuilder(JsonSchemaFactory.java:123) at com.github.fge.jsonschema.main.JsonSchemaFactory.byDefault(JsonSchemaFactory.java:113) at io.restassured.module.jsv.JsonSchemaValidatorSettings.<init>(JsonSchemaValidatorSettings.java:58) at io.restassured.module.jsv.JsonSchemaValidator$JsonSchemaValidatorFactory.createSettings(JsonSchemaValidator.java:277) at io.restassured.module.jsv.JsonSchemaValidator$JsonSchemaValidatorFactory.create(JsonSchemaValidator.java:289) at io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchema(JsonSchemaValidator.java:166) at io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchemaInClasspath(JsonSchemaValidator.java:117) at com.mycode.server.api.v1.RestEndpoint.getResponse(RestEndpoint.java:51) at com.mycode.server.api.v1.IssuersEndpointTests.getAllIssuers(IssuersEndpointTests.java:32) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) at org.junit.runners.ParentRunner.run(ParentRunner.java:363) at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by asirin48** [comment]
This was caused by older versions of guava on the file path. Adding the new library solved the issue
