### ISSUE TITLE
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1

### ISSUE THREAD

**Issue by pratikganganigithub** [rest-assured/rest-assured#1057]
Hello,

i am getting error as below in eclipse with rest assured 3.0.2 , let me know is there any solution is there ?

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/F:/Study%20Software/2%20REST%20Assured/REST%203.0.2/rest-assured-3.0.2-dist/rest-assured-3.0.2-deps/groovy-2.4.6.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at io.restassured.config.ObjectMapperConfig.<init>(ObjectMapperConfig.java:49)
	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:420)
	at demo.Basics.main(Basics.java:15)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

**Comment by arturmkr** [comment]
@pratikganganigithub , how did you fix this issue?

**Comment by poser55** [comment]
Would an update to the new version of Groovy help, the issue seems to be here:
https://issues.apache.org/jira/browse/GROOVY-8339
