### ISSUE TITLE
unable to user post from REST Assured

### ISSUE THREAD

**Issue by pradeepkommu** [rest-assured/rest-assured#1076]
I am new to Rest assured, I was able to get all the responses with GET service.
But for the POST i am getting below error. request you to please help.

public void testPOST(){
		baseURI="http://10.4.11.108:8093";
		Response res =given().log().all().
				header("Content-Type","application/json").
				header("x-tenant","XX").
				header("Authorization","Bearer "+key).
				body("{\"useAllotment\":false,\"commodity\":{\"commodityCode\":\"9203\"},\"shcs\":[],\"cargoType\":\"F\",\"sortType\":1,\"scheduleParams\":{\"flights\":[],\"bodyTypes\":[],\"departureDate\":\"2018-10-08 00:00:00\",\"origin\":{\"code\":\"DXB\"},\"destination\":{\"code\":\"BOM\"},\"flightExactMatch\":false},\"spaceParams\":{\"weight\":{\"unit\":{\"code\":\"K\"},\"value\":100},\"volume\":{\"unit\":{\"code\":\"CM\"},\"value\":0.599988},\"pieces\":\"10\"},\"priceParams\":{\"productCode\":\"GCR\",\"mop\":\"PP\",\"declaredValue\":{\"amount\":0,\"currency\":\"AED\"}},\"document\":{\"documentType\":\"AWB\",\"documentPrefix\":\"888\",\"documentNumber\":\"UNK\"},\"goodsDescription\":\"TOYS. GAMES\",\"pageInfo\":{\"pageNumber\":1,\"pageSize\":\"15\"}}").
				when().
				post("/services/cargo/offers").
				then().assertThat().statusCode(200).
				extract().response();
		System.out.println("responce "+res.asString());
	}

OutPut:

Request method:	POST
Request URI:	http://10.4.11.108:8093/services/cargo/offers
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		x-tenant=XX
				Authorization=Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3R5cGUiOiJTVERSRCIsInVzZXJfaWQiOjEyNjk1MCwidXNlcl9uYW1lIjoiUFJBREVFUCIsInNjb3BlIjpbIm9wZW5pZCIsInJlYWQiLCJ3cml0ZSJdLCJuYW1lIjoiUFJBREVFUCIsInNlc3Npb25faWQiOiIxNTM5MzI4NTQ1OTU3LjAuODY0MTcxNjkyMzQzODg1OSIsImV4cCI6MTUzOTE3Mjk4MSwiYXV0aG9yaXRpZXMiOlsiQ0hBTkdFX1VOSVRTIiwiRVhQT1JUX0ZMSUdIVF9PUFMiLCJFVkxfVklFV19BTE5fUlNOIiwiU0hDX01PRElGWSIsIkRFTEVURV9JVElORVJBUllfQUZURVJfQVJSIiwiREdEX0VYQ1NfU0FWRSIsIlVQREFURV9CT09LSU5HX1BSSU9SSVRZIiwiRVZMX1ZJRVdfUkFUSURfUkdFIiwiVFJOU1RfUEVSTV9PVlIiLCJJR05PUkVfTVZUX1NUU19GT1JfUkVTX0FNRU5EIiwiRVZMX1JFUV9CTFdfSFJEX1JBVCIsIkFMT1RfQVBSVl9TVE4iLCJDTkVFX0FDUFRfT1ZSIiwiT1ZFUlJJREVfSU1QX0FXQl9EQVRBIiwiU0hDX0RFTEVURSIsIlNLWVBPVUNIX0RFTEVURSIsIkFNRF9EQVRBX1JDUyIsIkJPT0tJTkdfQ0JWIiwiQU1EX0RBVEFfRkxUX0NMT1NFRCIsIlJFTU9WRV9JVE5SWV9DQU8iLCJCS05HX1NUQVRVU19DSE5HIiwiVklFV19ISURFX0JMT0NLIiwiR1JQX1JFQk9PSyIsIk9WUl9VTERfQ09NUEFUIiwiQUxMT1dfUFJJTlRfQkFSQ09ERV9CRUZPUkVfUkNTIiwiQ0FOQ0VMX0JPT0tJTkciLCJTSENfQ1JFQVRFIiwiR0VUX05FWFRfQVdCIiwiTElWRV9BTk1MX09WUiIsIk9WUl9NQ1RfQ0hFQ0siLCJER0RfRVhDU19BUFJWTCIsIkVYUE9SVF9TSElQX09QUiIsIlJFU19PTkxfQU1FTkQiLCJBTExPV19DVUJJU0NBTl9RVFlfVVBEQVRFIl0sImp0aSI6IjFlNmRkYWFmLTRkMWUtNGRkZi1iZGNlLWEyMGRkMmNkNmU3MyIsImNsaWVudF9pZCI6Im1lcmNhdG9yIiwidGVuYW50X2NvZGUiOiJYWCIsImRlZmF1bHRfc3RhdGlvbiI6IkRYQiJ9.BoLbyZkLRl7YRv-xzPinYsdhbMOEV9R92-ZdYr_nP9kNCVbfbTqFwbekxjoGiaW92laicdxafXYNBlgYl37QIzveSV6Aaaq-yvf_UlehTzvano_Q4fhtuQ4uAbnkMsOINdKHOY4LPaTUdqxlNW0oekORBSkzva7mr4GWC9yYDObFFGxRBH6xMs2HkkJZFHmCOeHjz7IDpENpLKDSdFG_Bnx97vF-H8OxsG-fm7YBz5z1VLJvHGKkVApXtkoVq6WCqESU_rbi-mdTpoSOTDM-hHfAY3Qj5tJ_jshVODRrVB11Iz5Xwt_ruAyWB5MxnqCfvlmQX2OOG6-oSNlQtUyF3Q
				Accept=*/*
				Content-Type=application/json; charset=UTF-8
Cookies:		<none>
Multiparts:		<none>
Body:
{
    "useAllotment": false,
    "commodity": {
        "commodityCode": "9203"
    },
    "shcs": [
        
    ],
    "cargoType": "F",
    "sortType": 1,
    "scheduleParams": {
        "flights": [
            
        ],
        "bodyTypes": [
            
        ],
        "departureDate": "2018-10-08 00:00:00",
        "origin": {
            "code": "DXB"
        },
        "destination": {
            "code": "BOM"
        },
        "flightExactMatch": false
    },
    "spaceParams": {
        "weight": {
            "unit": {
                "code": "K"
            },
            "value": 100
        },
        "volume": {
            "unit": {
                "code": "CM"
            },
            "value": 0.599988
        },
        "pieces": "10"
    },
    "priceParams": {
        "productCode": "GCR",
        "mop": "PP",
        "declaredValue": {
            "amount": 0,
            "currency": "AED"
        }
    },
    "document": {
        "documentType": "AWB",
        "documentPrefix": "888",
        "documentNumber": "UNK"
    },
    "goodsDescription": "TOYS. GAMES",
    "pageInfo": {
        "pageNumber": 1,
        "pageSize": "15"
    }
}
FAILED: testPOST
java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <505>.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:483)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:123)
	at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:131)
	at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:119)
	at apicalls.offerSearch.testPOST(offerSearch.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by pumano** [comment]
First of all:I highly recommend you to remove API KEY (Authorization Bearer) from this issue (due to security reason)
Second: check 505 http status description here: https://httpstatuses.com/505
