### ISSUE TITLE
Error to read HAL responses.

### ISSUE THREAD

**Issue by daibertdiego** [rest-assured/rest-assured#1083]
I'm trying to read a HAL response in my integration tests and I'm getting the following error:
`om.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "_embedded" (class org.springframework.hateoas.Resources), not marked as ignorable (2 known properties: "links", "content"])
 at [Source: (String)"{
  "_embedded" : {
    "userApis" : [ {
      "email" : "admin@email.com",
      "name" : "Test User Ibliss",
      "profile" : {
        "_links" : {
          "self" : {
            "href" : "http://127.0.0.1:8080/v1/profiles/577ad992f5897949670a6e2f"
          }
        },
        "profile_id" : "577ad992f5897949670a6e2f",
        "profile_name" : "MASTER"
      },
      "team" : [ {
        "_links" : {
          "self" : {
            "href" : "http://127.0.0.1:8080/v1/teams/5bd3262101e1d8"[truncated 765 chars]; line: 2, column: 18] (through reference chain: org.springframework.hateoas.Resources["_embedded"])`

I'm using this code to read the response:

`Response responseAPI = RestAssured.given().that()
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .accept(MediaTypes.HAL_JSON_VALUE)
                .header("Authorization", "Bearer " + apiToken)
                .get(API_URL + "/users");

        Resources<Resource<UserApi>> userApiList = responseAPI.as(new Resources<Resource<UserApi>>.getClass);
`

There is a right way to read this HAL response and transform again in my Java objects?

Thank you.

**Comment by johanhaleby** [comment]
What does the `Resources`, `Resource` and `UserApi` look like?

**Comment by johanhaleby** [comment]
You could also also try the latest snapshot, `3.2.1-SNAPSHOT` after having added the following repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

then do:

```java
Resources<Resource<UserApi>> userApiList = responseAPI.as(new TypeRef<Resources<Resource<UserApi>>>() {} );
```

**Comment by daibertdiego** [comment]
Hi, thank you for your fast response. I tried to use this way after update my libs to 3.2.1-SNAPSHOT and I'm getting this error after executing your suggestion:

'''
 Resources<Resource<UserApi>> userApiList = response.as(new TypeRef<Resources<Resource<UserApi>>>() {
        });
'''

'''
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "_embedded" (class org.springframework.hateoas.Resources), not marked as ignorable (2 known properties: "links", "content"])
 at [Source: (String)"{
  "_embedded" : {
    "userApis" : [ {
      "email" : "admin@email.com",
      "name" : "Test User Ibliss",
      "profile" : {
        "_links" : {
          "self" : {
            "href" : "http://127.0.0.1:8080/v1/profiles/577ad992f5897949670a6e2f"
          }
        },
        "profile_id" : "577ad992f5897949670a6e2f",
        "profile_name" : "MASTER"
      },
      "team" : [ {
        "_links" : {
          "self" : {
            "href" : "http://127.0.0.1:8080/v1/teams/5bd718cb9c04da"[truncated 765 chars]; line: 2, column: 18] (through reference chain: org.springframework.hateoas.Resources["_embedded"])

	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
	at com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)
	at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:47)
	at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
	at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
	at io.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)
	at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:204)
	at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)
	at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:57)
	at io.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at io.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)
	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:220)
	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl$as$5.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:237)
	at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:179)
	at br.com.ibliss.api.UserApiTest.findAllTest(UserApiTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
'''

My UserAPI is like that:

'''
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class UserApi extends ResourceSupport implements Serializable {

    private static final long serialVersionUID = 407412034973803980L;

    @JsonProperty("user_id")
    private ObjectId userId;

    private String email;

    private String name;

    private ProfileApi profile;

    private List<TeamApi> team = new ArrayList<>();

    @JsonProperty("bu_root")
    private boolean rootCompany;

    @JsonProperty("expiration_date")
    private LocalDateTime expirationDate;

    private boolean enabled;

    public UserApi(User user, Profile profile, List<Team> teamList) throws ServiceException {
        this.add(linkTo(methodOn(UsersApiResource.class).findById(user.getId().toString())).withSelfRel());
        this.userId = user.getId();
        this.email = user.getEmail();
        this.name = user.getName();
        this.rootCompany = user.isRootCompany(profile.getCompany());
        this.expirationDate = user.getExpirationDate();
        this.profile = new ProfileApi(profile);
        this.enabled = user.isEnable();
        for (Team team : teamList) {
            this.team.add(new TeamApi(team, user));
        }
    }
}
'''

And my API Controller is like this:

''''
@GetMapping()
    public ResponseEntity<Resources<Resource<UserApi>>> list() throws ServiceException {
        List<Resource<UserApi>> resourceList = service.findAll().stream().map(api -> new Resource<>(api)).collect(Collectors.toList());
        return ResponseEntity.ok(new Resources<>(resourceList, linkTo(methodOn(UsersApiResource.class).list()).withSelfRel()));
    }
''''
