### ISSUE TITLE
Cannot initialize RestAssured

### ISSUE THREAD

**Issue by mafupi** [rest-assured/rest-assured#1167]
I am trying to initialize RestAssured but it blows up when setting the baseUri:
`
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/restassured/internal/http/HTTPBuilder.patch(Ljava/util/Map;Lgroovy/lang/Closure;)Ljava/lang/Object; @28: invokespecial
  Reason:
    Type 'org/apache/http/client/methods/HttpPatch' (current frame, stack[3]) is not assignable to 'org/apache/http/client/methods/HttpRequestBase'
  Current Frame:
    bci: @28
    flags: { }
    locals: { 'io/restassured/internal/http/HTTPBuilder', 'java/util/Map', 'groovy/lang/Closure', '[Z' }
    stack: { uninitialized 4, uninitialized 4, 'io/restassured/internal/http/HTTPBuilder', 'org/apache/http/client/methods/HttpPatch', 'java/lang/Object', 'java/util/Map', 'java/util/Map' }
  Bytecode:
    0x0000000: b802 254e bb00 3959 2abb 004a 59b7 004b
    0x0000010: 2ab4 0009 2ab4 0010 2ab4 000e b700 3c3a
    0x0000020: 042d 102b 0454 1904 b200 45b6 0046 b600
    0x0000030: 472d 102c 0454 1904 2bb6 003d 2cc7 000b
    0x0000040: 2d10 2d04 54a7 0036 2d10 2e04 5419 04b6
    0x0000050: 003e b200 3fb6 0048 2cb9 0040 0300 572d
    0x0000060: 102f 0454 1904 b600 3eb2 004c b600 482c
    0x0000070: b900 4003 0057 2d10 3004 542a 1904 b600
    0x0000080: 412d 1031 0454 b0                      
  Stackmap Table:
    append_frame(@72,Object[#551],Object[#57])
    same_frame(@123)

	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:49)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:36)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:353)
 `
This is my setup is:

`
RestAssured.baseURI = "http://localhost"
        RestAssured.port = 8080
        RestAssured.basePath = "/api"
        RestAssured.urlEncodingEnabled = false
`

**Comment by mafupi** [comment]
It turned I was using httpclient-android as opposed httpclient
