### ISSUE TITLE
Content Type issue - getting serialization exception

### ISSUE THREAD

**Issue by ssdtrdhinesh** [rest-assured/rest-assured#1176]
When sending the 'ContentType' as EMPTY then getting the following exception:
      _

> java.lang.IllegalArgumentException: Cannot serialize because cannot determine how to serialize content-type 
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
> 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
> 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
> 	at io.restassured.internal.mapping.ObjectMapping.serialize(ObjectMapping.groovy:163)
> 	at io.restassured.internal.mapping.ObjectMapping$serialize.call(Unknown Source)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
> 	at io.restassured.internal.RequestSpecificationImpl.body(RequestSpecificationImpl.groovy:750)

_

**But when tried with POSTMAN, getting the proper error response.**
![ContentType_issue](https://user-images.githubusercontent.com/11424605/58549441-6b67fa80-8203-11e9-9509-d2c235d065f8.jpg)

**Comment by johanhaleby** [comment]
@ssdtrdhinesh What does your request look like?

**Comment by ssdtrdhinesh** [comment]
@johanhaleby thanks for the response and apologies for delay.

**Details:**
**Use Case 1**: _Content Type header is not present_
- when we don't specify the content type, we can see that the default 'text/plain' is added.
_

> org.apache.http.headers - >> Cache-Control: no-store
> org.apache.http.headers - >> Accept: */*
> org.apache.http.headers - >> Accept-Language: en-US
> org.apache.http.headers - >> Content-Type: text/plain
> org.apache.http.headers - >> Content-Length: 89
> org.apache.http.headers - >> Host: localhost:8095
> org.apache.http.headers - >> Connection: Keep-Alive
> org.apache.http.headers - >> User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_181)

_

**Use Case 2**: _Content Type header is present, but value is EMPTY ('')._
- we are getting the serialization exception as the request object is not formed.

> org.apache.http.headers - >> Cache-Control: no-store
> org.apache.http.headers - >> Accept: */*
> org.apache.http.headers - >> Accept-Language: en-US
> org.apache.http.headers - **>> Content-Type:**                                        --> this causes the exception
> org.apache.http.headers - >> Content-Length: 89
> org.apache.http.headers - >> Host: localhost:8095
> org.apache.http.headers - >> Connection: Keep-Alive
> org.apache.http.headers - >> User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_181)

getting the following exception when requesting:
"      java.lang.IllegalArgumentException: Cannot serialize because cannot determine how to serialize content-type 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at io.restassured.internal.mapping.ObjectMapping.serialize(ObjectMapping.groovy:163)
	at io.restassured.internal.mapping.ObjectMapping$serialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at io.restassured.internal.mapping.ObjectMapping$serialize.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.body(RequestSpecificationImpl.groovy:750)"

**Comment by johanhaleby** [comment]
This is because rest assured cannot know how to serialize the `bodyMap` unless you specify a content-type. You can try serializing it manually.
