### ISSUE TITLE
kotlin-extension: Extract doesn't return if body is used in Then block

### ISSUE THREAD

**Issue by jethroindc** [rest-assured/rest-assured#1212]
Having an issue where I get the following stack trace:

```
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document

	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at io.restassured.path.json.JsonPath$get$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.path(RestAssuredResponseOptionsGroovyImpl.groovy:405)
	at io.restassured.internal.RestAssuredResponseOptionsImpl.path(RestAssuredResponseOptionsImpl.java:230)
	at com.abc.EvalAddressTest$getSession$4.invoke(EvalAddressTest.kt:36)
	at com.abc.EvalAddressTest$getSession$4.invoke(EvalAddressTest.kt:14)
	at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt.Extract(RestAssuredKotlinExtensions.kt:66)
	at com.abc.EvalAddressTest.getSession(EvalAddressTest.kt:35)
	at com.abc.EvalAddressTest.test evaluate address HO3(EvalAddressTest.kt:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:80)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	... 36 more
```

when trying to return the value of an element using `Extract` and `path` but it only occurs when `body` is used in the `Then` clause

```
fun getSession( path: String ): String {
        return Given {
            baseUri("http://localhost:7070")
            header("Content-Type", ContentType.JSON)
            header("x-trace-id", UUID.randomUUID().toString())
            body(this.javaClass.getResourceAsStream("/evaluate.json"))
        } When {
            post("/v1/evaluateaddress/evaluate")
        } Then {
            log()
            statusCode(200)
            body("quoteHeader.sessionHash", `is`(not(emptyString())))
        } Extract {
            path("quoteHeader.sessionHash")
        }
    }
```

will fail while

```
fun getSession( path: String ): String {
        return Given {
            baseUri("http://localhost:7070")
            header("Content-Type", ContentType.JSON)
            header("x-trace-id", UUID.randomUUID().toString())
            body(this.javaClass.getResourceAsStream("/evaluate.json"))
        } When {
            post("/v1/evaluateaddress/evaluate")
        } Then {
            log()
            statusCode(200)
        } Extract {
            path("quoteHeader.sessionHash")
        }
    }
```

will return the correct response

**Comment by jethroindc** [comment]
Also wanted to add that the same code works in Java

```
 return given()
                .header("Content-Type", ContentType.JSON)
                .header("x-trace-id", UUID.randomUUID().toString())
                .baseUri("http://localhost")
                .port(7070)
                .body(stream)
        .when()
                .post("/v1/evaluateaddress/evaluate")
        .then()
                .statusCode(200)
                .body("quoteHeader.sessionHash", is(not(emptyString())))
        .extract()
                .path("quoteHeader.sessionHash");
```

**Comment by vrto** [comment]
+1

**Comment by johanhaleby** [comment]
I'll hopefully have time to dig into this today

**Comment by johanhaleby** [comment]
I've fixed this in master now and published a new snapshot. Please try version `4.1.2-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

I'm going to close this issue, please reopen if you think it's the wrong decision.
