### ISSUE TITLE
unable to run rest assured test with authentication on 4.3.0

### ISSUE THREAD

**Issue by mverwaerde** [rest-assured/rest-assured#1290]
On every authenticated test with 

`	private RequestSpecification givenCommon() {
		return given()
				.redirects().follow(false)
				.port(this.port);
	}
`

we've got this stack : 

`java.lang.AbstractMethodError: Receiver class io.restassured.internal.ResponseParserRegistrar does not define or inherit an implementation of the resolved method abstract getProperty(Ljava/lang/String;)Ljava/lang/Object; of interface groovy.lang.GroovyObject.

	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
	at io.restassured.internal.ResponseParserRegistrar.<init>(ResponseParserRegistrar.groovy:44)
	at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1448)
	at io.restassured.RestAssured.given(RestAssured.java:653)`

It seems groovy migration on 4.3.0 don't work with this implementation.

**Comment by oliverlockwood** [comment]
For anyone else discovering this: it was closed as a duplicate of #1283
