### ISSUE TITLE
Severe Runtime Exception when building a new RequestSpecification with 4.3.0 version

### ISSUE THREAD

**Issue by sahlouls** [rest-assured/rest-assured#1294]
Hi,

After upgrading to `4.3.0` version, I'm getting a new severe exception when running post requests

Usage causing the exception
```
String baseUri = "MY_URL";
RequestSpecification spec = new RequestSpecBuilder().setBaseUri(baseUri).build();
```

The exception
```
Mar 23, 2020 11:41:11 AM org.aspectj.weaver.tools.Jdk14Trace error
SEVERE: org/codehaus/groovy/runtime/callsite/AbstractCallSite
java.lang.RuntimeException: bad non-abstract method with no code: void org.codehaus.groovy.runtime.callsite.AbstractCallSite.<init>(org.codehaus.groovy.runtime.callsite.CallSiteArray, int, java.lang.String) on public class org.codehaus.groovy.runtime.callsite.AbstractCallSite
	at org.aspectj.weaver.bcel.LazyMethodGen.<init>(LazyMethodGen.java:223)
	at org.aspectj.weaver.bcel.LazyClassGen.<init>(LazyClassGen.java:362)
	at org.aspectj.weaver.bcel.BcelObjectType.getLazyClassGen(BcelObjectType.java:563)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1706)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1657)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1422)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1196)
	at org.aspectj.weaver.tools.WeavingAdaptor.getWovenBytes(WeavingAdaptor.java:551)
	at org.aspectj.weaver.tools.WeavingAdaptor.weaveClass(WeavingAdaptor.java:387)
	at org.aspectj.weaver.loadtime.Aj.preProcess(Aj.java:116)
	at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:51)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:636)
	at org.codehaus.groovy.reflection.SunClassLoader.define(SunClassLoader.java:94)
	at org.codehaus.groovy.runtime.callsite.GroovySunClassLoader.loadAbstract(GroovySunClassLoader.java:72)
	at org.codehaus.groovy.runtime.callsite.GroovySunClassLoader.<init>(GroovySunClassLoader.java:54)
	at org.codehaus.groovy.runtime.callsite.GroovySunClassLoader.<init>(GroovySunClassLoader.java:49)
	at org.codehaus.groovy.runtime.callsite.GroovySunClassLoader.lambda$static$0(GroovySunClassLoader.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.runtime.callsite.GroovySunClassLoader.<clinit>(GroovySunClassLoader.java:37)
	at org.codehaus.groovy.runtime.callsite.CallSiteGenerator.isCompilable(CallSiteGenerator.java:256)
	at org.codehaus.groovy.reflection.CachedMethod.createStaticMetaMethodSite(CachedMethod.java:312)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.createStaticMetaMethodSite(StaticMetaMethodSite.java:112)
	at groovy.lang.MetaClassImpl.createStaticSite(MetaClassImpl.java:3496)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:74)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:156)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:21)
	at io.restassured.config.SSLConfig.<init>(SSLConfig.java:192)
	at io.restassured.config.SSLConfig.<init>(SSLConfig.java:184)
	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:421)
	at io.restassured.builder.RequestSpecBuilder.<init>(RequestSpecBuilder.java:79)
```

Any ideas how to fix this, thanks

**Comment by xiongzl-github** [comment]
我也遇到了这个问题, 请问怎么解决?

**Comment by ansonliao** [comment]
Downgraded to version `4.2.0` and this error message is gone away, but it is not a good solution, hope can solve this problem soon.

https://stackoverflow.com/questions/61457462/console-error-when-running-rest-assured-api-test-with-testng

**Comment by tinashec** [comment]
Has this been resolved? Experiencing this using `5.3.0`

**Comment by anthonycholakov** [comment]
Hi, I was having the exact same problem by using - openjdk version "1.8.0_352". When I've updated to Java 11 the problem was resolved. So you might consider upgrading your Java version and hope this would solve your issue as well.
