### ISSUE TITLE
Not able to read the response through Json Path, Getting null pointer exception

### ISSUE THREAD

**Issue by ChrisShanVi** [rest-assured/rest-assured#1295]
Im using the rest assured version 4.3
My code:
public class WeatherTest {
	Response jsonresponse;
	
  @Test(groups = {"RestAPI_Test01"})
  public void testGETRequest() {
    Response jsonresponse = RestAssured.given()
			.when()
			.get("http://restapi.demoqa.com/utilities/weather/city/Hyderabad").then()
			.extract()
			.response();
    String strJSONResponse = jsonresponse.getBody().asString();
    System.out.println(strJSONResponse);
    
   String temp = new JsonPath(strJSONResponse).get("WindSpeed");
   System.out.println(temp);
}
Getting the below exception, while trying to read the response through json path.

java.lang.NullPointerException: Cannot invoke method startsWith() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:53)
	at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
	at Test_RestAssured.java.WeatherTest.testGETRequest(WeatherTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner$$Lambda$44.0000000010222C70.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by corporate-gadfly** [comment]
Pretty sure, I have the same issue. I rewrote your test as follows _(to be more concise)_:
```
given()
        .log().all()
.when()
        .get("http://restapi.demoqa.com/utilities/weather/city/Hyderabad")
.then()
        .log().all()
        .statusCode(OK.getStatusCode())
        .contentType(JSON)
        .body("City", equalTo("Hyderabad"))
        .body("WindSpeed", endsWith("Km per hour"));
```
And it fails with identical stack trace with `4.3.0` but passes with `4.2.0`.

**Comment by corporate-gadfly** [comment]
groovy bumped from `2.5.8` to `3.0.2` when rest assured bumped to `4.3.0`.

**Comment by corporate-gadfly** [comment]
Gets weirder. With `4.3.0`, fails with:
```openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200122_439 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)
```
and passes with:
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

**Comment by corporate-gadfly** [comment]
@ChrisShanVi : For me, the above test case only fails with Eclipse OpenJ9 version of AdoptOpenJDK 1.8.0_242. Do you happen to be blessed with the same JVM?

**Comment by ChrisShanVi** [comment]
> @ChrisShanVi : For me, the above test case only fails with Eclipse OpenJ9 version of AdoptOpenJDK 1.8.0_242. Do you happen to be blessed with the same JVM?

yeah, my Java version is  AdoptOpenJDK 1.8.0_202

**Comment by corporate-gadfly** [comment]
That's fine, but is it AdopOpentJDK or AdoptOpenJDK OpenJ9?

**Comment by mageddo** [comment]
The Issue is related to `openj9` JVM, switch to Hotspot JVM fix the problem

Failing JVM
```
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0, JRE 11 Linux amd64-64-Bit Compressed References 20200116_433 (JIT enabled, AOT enabled)
```

Working JVM
```
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
```

**Comment by gmussi** [comment]
I have the exact same issue and i am using 

```
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 14 Windows 10 amd64-64-Bit Compressed References 20200422_50 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 5757187cae based on jdk-14.0.1+7)
```

Downgrading to `4.2.0` also fixed the problem for me. Thanks, @corporate-gadfly .

**Comment by zeapo** [comment]
I'm able to replicate the same issue with OpenJ9, regardless of the version of rest-assured.
