### ISSUE TITLE
JsonPath not working within test scopes in AdoptOpenJDK 11-j9, 12-j9

### ISSUE THREAD

**Issue by Balky79** [rest-assured/rest-assured#1307]
Hi, 

I am trying to move from Java 8 to a higher version, and I tried to run my test that run perfectly in Java 8. 

I'm using restAssured 4.2.0

I tried shifting to Java 11, and 12, both AdoptOpenJDK versions, namely: 11.0.6.j9 and 12.0.2.j9.

Code that runs fine in J8 is: 

```
String response = given()./*log().all().*/header("Content-Type", "application/x-www-form-urlencoded").header("bypassjwt", "true").
                when().get("/search/attachments/v1.0").
                then()./*log().all().*/assertThat().statusCode(200).extract().response().asString();

//        JsonPath js=Utils.rawToJson(response)/*.setRootPath("pageResource").using(new JsonPathConfig("UTF-8"))*/;
        JsonPath js=new JsonPath(response);
String pageSize = js.getString("pageResource");
```

Where I'm reading the value of Json that is passed in response from API test.

In both J11 and J12 it fails with:

```
Cannot invoke method startsWith() on null object
java.lang.NullPointerException: Cannot invoke method startsWith() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:53)
	at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
	at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
	at test_searchEndpoint.test_basicPing(test_searchEndpoint.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

To make it more interesting, I moved the whole thing to regular Java Class, and it runs there as well, but when it's within test scope of the project, it fails. 

I tried moving the Json Parsing logic only into the Utility Java Class, that would sit outside of test scope, but would be run via tests (to make use of JUnit) - fails with the same error.

Analysing the object, I can see that data is there, it's part of the object, but it just fails somewhere else, and I can't figure out where. 

If this is known issue or there is a way to get around it, feel free to close it, but please do let me know how to make it work within test scopes.

Thanks, 

Igor

**Comment by slowtarget** [comment]
I'm also facing this issue .. existing tests that were passing with spring boot 2.5.1 dependencies are now failing with this error on spring boot 2.5.6, both are using rest assured 4.2.0, both on jdk 11

I've tracked down the source of the issue a little.

io/restassured/internal/path/json/JSONAssertion.groovy:53 has this within a catch block, but the exception has a null message, resulting in the thrown exception `Cannot invoke method startsWith() on null object`
`if (e instanceof NullPointerException && e.getMessage().startsWith("Cannot get property") `

The original exception is thrown from within a groovy shell while it is attempting to evaluate an expression that has worked before. 

failing test is using org.codehaus.groovy:groovy:3.0.9 , passing test is using 3.0.8

when debugging  I step into the method call `def res = sh.evaluate(expr)` on line 80 of JSONAssertion.groovy 
I end up in   AdoptOpenJDK\jdk-11.0.6+10\lib\src.zip!\java.base\com\ibm\jit\JITHelpers.java  getLongFromObject(Object obj, long offset), where the object is the groovy shell and the offset is 0. 

So I excluded org.codehaus.groovy:groovy:3.0.9 from the build and brought in 3.0.8 - and I still get the same error.

Its only `.body(...)` assertions that seem to be affected, so we can use result matchers as a workaround. We have hundreds of tests that were working and now are not passing.

**Comment by slowtarget** [comment]
I switched out of open j9 and tests now pass.

**Comment by johanhaleby** [comment]
You probably need to override the groovy version that Spring Boot specifies
by default. In your pom.xml set the groovy.version property to 3.0.8 (or
later):

<properties>
    <groovy.version>3.0.8</groovy.version>
    ....
