### ISSUE TITLE
Cannot invoke method getObjectMapperConfig() on null object for response build through ResponseBuilder Class

### ISSUE THREAD

**Issue by nvora** [rest-assured/rest-assured#1335]
**I am converting response received through different library and then trying to convert it into rest response through below code**

private Response convertPrismResponseToRestAssuredResponse(DifferenResponse differenResponse) {
	ResponseBuilder responseBuilder = new ResponseBuilder();
	return responseBuilder.setBody(differenResponse.getResponseEntityAsString()).setContentType(ContentType.JSON)
			.setStatusCode(differenResponse.getResponseCode())
			.setHeaders(convertPrismHeaderToRestAssuredHeaders(differenResponse.getHeaders())).build();
}

**And trying to get error by setting jsonPath root for same, but its throwing null pointer excption.**

jsonPathEvaluator = response.jsonPath().setRoot("Errors");

**jsonPath is working properly with below** 

public Response getRequest(String requestUrl, ContentType acceptFormat, Map<String, Object> headers) {
	RequestSpecification requestSpec = builder.build().accept(acceptFormat).contentType(ContentType.JSON);
	Response response = RestAssured.given().headers(headers).when().relaxedHTTPSValidation().log().all().get(requestUrl);
	return response;

**Stacktrace**
Cannot invoke method getObjectMapperConfig() on null object
java.lang.NullPointerException: Cannot invoke method getObjectMapperConfig() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.jsonPath(RestAssuredResponseOptionsGroovyImpl.groovy:358)
	at io.restassured.internal.RestAssuredResponseOptionsImpl.jsonPath(RestAssuredResponseOptionsImpl.java:176)

**Comment by nvora** [comment]
Issue was resolved with version 4.10 so closed.
