### ISSUE TITLE
While Running the program getting an error in Console "Exception in thread "main" java.lang.NoClassDefFoundError: io/restassured/RestAssured"

### ISSUE THREAD

**Issue by AutomationTester09** [rest-assured/rest-assured#1379]
Eclipse editor

Error :
Exception in thread "main" java.lang.NoClassDefFoundError: io/restassured/RestAssured
	at Basics.main(Basics.java:16)
Caused by: java.lang.ClassNotFoundException: io.restassured.RestAssured
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

**Comment by satkartarsingh** [comment]
Is the issue resolved ? I am also facing the same issue !

**Comment by adacris25** [comment]
Hi! 
I faced the same issue as you or at least looking at the error it seems the same. In my case the external jars were not added properly, but after following the below steps everything worked when the project was compiled.

1. create a folder called lib in your project folder.
2. copy to this folder all the jar files you need.
3. refresh your project in eclipse.
4. select all the jar files, then right click on one of them and select Build Path -> Add to Build Path
