### ISSUE TITLE
expect status code 400 but restassured throw io.restassured.internal.http.HttpResponseException: Bad Request

### ISSUE THREAD

**Issue by serhatozdursun** [rest-assured/rest-assured#1381]
Hello,

i want to check request return 400 if i send request with wrong id and request return 400 but restassured throw 

io.restassured.internal.http.HttpResponseException: Bad Request

	at io.restassured.internal.http.HTTPBuilder.defaultFailureHandler(HTTPBuilder.java:627)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1262)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1042)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1136)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1029)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at groovy.lang.Closure$call$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)

my test code;

RestAssured
                .given()
                .relaxedHTTPSValidation()
                .expect()
                .statusCode(expectedStatusCode)
                .when()
                .get(endPoint + "/" + id);

**Comment by anilemreciftci** [comment]
Hi @serhatozdursun did you solve this problem, i am having the same issue?
