### ISSUE TITLE
Rest Assured fails with "IllegalArgumentException" when Content-Type is set as "application/x-amz-json-1.1"

### ISSUE THREAD

**Issue by wilfredclement7** [rest-assured/rest-assured#1440]
**Request :**

 ```
RequestSpecBuilder abc = new RequestSpecBuilder();
        abc.addHeader("Accept-Language", "en-US");
        abc.addHeader("Accept-Encoding", "gzip, deflate, br");
        abc.addHeader("amz-sdk-request", "attempt=1; max=3r");
        abc.addHeader("Content-Type", "application/x-amz-json-1.1");
        RequestSpecification def = abc.build();

        RestAssured.given().log().all().header("Content-Type","application/x-amz-json-1.1")
                .config(RestAssured.config().encoderConfig(
                        encoderConfig().encodeContentTypeAs("application/x-amz-json-1.1", ContentType.)))
                .spec(def).when().body(request).post(URL).then().log().all();
```

**Error :**

```
Exception in thread "main" java.lang.IllegalArgumentException: Don't know how to encode {"disable_captcha":"true","Value":"disable_captcha"} as a byte stream.

Please use EncoderConfig (EncoderConfig#encodeContentTypeAs) to specify how to serialize data for this content-type.
For example: "given().config(RestAssured.config().encoderConfig(encoderConfig().encodeContentTypeAs("application/x-amz-json-1.1", ContentType.TEXT))). .."
    at io.restassured.internal.http.EncoderRegistry.encodeStream(EncoderRegistry.java:132)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
```

I have tried the EncoderConfig methods  and it is not working

The same request is working fine in `POSTMAN` and `JMETER`

**Comment by tomaszwojciechowski** [comment]
It will work if you'll move .config just before .post in your code:
`                .config(RestAssured.config().encoderConfig(
                        encoderConfig().encodeContentTypeAs("application/x-amz-json-1.1", ContentType.JSON)))
                .post(URL)`

**Comment by feeroz123** [comment]
> It will work if you'll move .config just before .post in your code:
> ` .config(RestAssured.config().encoderConfig( encoderConfig().encodeContentTypeAs("application/x-amz-json-1.1", ContentType.JSON))) .post(URL)`

Thanks for the solution. One small change I had to add was this:

```
Response response = given().spec(reqSpec).body(reqBody).log().all().when()
					.config(RestAssured.config()
							.encoderConfig(**EncoderConfig.**encoderConfig()
									.encodeContentTypeAs("application/x-amz-json-1.1", ContentType.JSON)))
					.post().then().log().all().spec(resSpec).extract().response();
```
