### ISSUE TITLE
rest-assured 4.3.0 failed to initialize on Java 16

### ISSUE THREAD

**Issue by fmhwong** [rest-assured/rest-assured#1452]
Running rest-assured 4.3.0 on OpenJDK Runtime Environment (16+36-202102262341) and it failed to initialize

```
java.lang.ExceptionInInitializerError: null
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1500)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1486)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at io.restassured.internal.assertion.AssertParameter.notNull(AssertParameter.groovy:21)
	at io.restassured.config.SSLConfig.<init>(SSLConfig.java:192)
	at io.restassured.config.SSLConfig.<init>(SSLConfig.java:184)
	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:420)
	at org.eclipse.microprofile.metrics.test.MpMetricTest.setup(MpMetricTest.java:132)
```

**Comment by fmhwong** [comment]
Closing this as this seems to happen on older releases only.
