### ISSUE TITLE
JsonPath cannot handle wildcards?

### ISSUE THREAD

**Issue by Auzzy** [rest-assured/rest-assured#1490]
I can't figure out how to get JsonPath to handle wildcards, despite the Javadocs saying it uses GPath, whose docs say it supports them.

The JSON I need to navigate is something like:
`
{
    "qa": {
        "all": {
            "inMaintenance": true,
            "windows": [
                {
                    "subject": "window-subject",
                    "environment": "qa"
                }
            ]
        }
    },
    "production": {
        "database": {
            "inMaintenance": true,
            "windows": [
                {
                    "subject": "window-subject",
                    "environment": "production"
                }
            ]
        }
    }
}
`

Once I get the Response object, I'm trying to get at the subject in both stanzas. The top level keys (qa and production, in this example) can change, as can the keys below them (all and database, in this example). As such, I'm trying to get at all the subjects with this:
`
Response response = ...;
List<String> subjects = response.jsonPath().get("*.*.windows.subject");
`

However, that results in an IllegalArgumentException.
`
java.lang.IllegalArgumeas sntException:
Invalid JSON expression:
Script1.groovy: 1: Unexpected input: '                         *.' @ line 1, column 27.
                            *.all.inMaintenance
                             ^

1 error

        at com.akamai.pulsar.dashboard.core.DashboardAdminProvMaintenanceWindows.figureOutJsonPath(DashboardAdminProvMaintenanceWindows.java:412)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException:
startup failed:
Script1.groovy: 1: Unexpected input: 'restAssuredJsonRootObject.*.' @ line 1, column 27.
   restAssuredJsonRootObject.*.all.inMaintenance
                             ^

1 error
`

I've tried some other forms I've seen in various docs, such as the "chidlren()" method, or surrounding each path piece in single-quotes, all of which fail with some error or result in null. I'd appreciate any help you can provide!

RestAssured version: 4.4.0 (also tried with 4.3.3)
Java version: OpenJDK 1.8.0_282
Code is run using Maven 3.3.9.
Platform: Linux (Ubuntu 16.04)

**Comment by dp1506** [comment]
As the "windows" here is essentially an array, try using this - *.*.windows[0].subject.

**Comment by Auzzy** [comment]
The error is about the expression itself, not about a failure to operate on the data. It's failing to compile the expression, and the only reason I can figure is that Rest-Assured doesn't actually support wildcards in its JsonPath expressions.

I tried your suggest anyways, and sure enough, same result.

```
java.lang.IllegalArgumentException:
Invalid JSON expression:
Script1.groovy: 1: Unexpected input: '                         *.' @ line 1, column 27.
                            *.*.windows[0].subject
                             ^

1 error

        at com.akamai.pulsar.dashboard.core.DashboardAdminProvMaintenanceWindows.getActiveMaintenanceWindowsForEnvAndTargetType(DashboardAdminProvMaintenanceWindows.java:400)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException:
startup failed:
Script1.groovy: 1: Unexpected input: 'restAssuredJsonRootObject.*.' @ line 1, column 27.
   restAssuredJsonRootObject.*.*.windows[0].subject
                             ^

1 error
```

**Comment by kool79** [comment]
Rest assured does not use traditional json-path. It uses gpath or groovy-path.
Actually all expressions which we write should be a valid groovy expressions.
To evaluate gpath expression rest-assured executes the next steps:
1. place json object into **_restAssuredJsonRootObject_** variable
2. prepend string with your gpath expression with string "**_restAssuredJsonRootObject._**" . Note: dot is not used when your expression starts with index, like "[0].someField"
3. evaluates string from step2 as groovy expression.
As you can see from implementation we cannot use "*" here because they will not be valid. But instead you can use full power of [groovy collections](http://docs.groovy-lang.org/next/html/documentation/working-with-collections.html) 

P.S> full implementation is located in:  io.restassured.internal.path.json.JSONAssertion#getAsJsonObject
