### ISSUE TITLE
Support jakarta.xml.bind namespace (jakarta.xml.bind-api:3.x) to support Jersey 3.x test framework

### ISSUE THREAD

**Issue by devminded** [rest-assured/rest-assured#1531]
**Request**
Support **jakarta.xml.bind** namespace (jakarta.xml.bind-api:3.x, etc)

**Reason**
Jersey 3.x Test Framework uses jakarta.xml.bind-api:3.x and expects jakarta.xml.bind.* classes while Rest Assured uses 2.x and expects javax.xml.bind.* classes. When using a combination of these frameworks either jersey stops working or rest assured stops working.

```
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at io.restassured.config.ObjectMapperConfig.<init>(ObjectMapperConfig.java:53)
	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:421)
```

This bump should probably have been done with the release of Rest assured 4.x

**Comment by Ladicek** [comment]
Sounds like a duplicate of #1510 to me.

**Comment by agoncal** [comment]
Same happens with JSon-B. See #1651
