### ISSUE TITLE
Cannot add custom Content-Length header

### ISSUE THREAD

**Issue by iklimchuk** [rest-assured/rest-assured#1538]
restassured version 4.4.0

STR:
1. try to fire the post request with custom "Content-Length" header

given(request.build())
        .header("Content-Length", body.length())
        .log().all()
        .post()...;

Actual result: request fails with exception: **Caused by: org.apache.http.ProtocolException: Content-Length header already present**

Logs output for a case w/o custom Content-Length header:

```
Request method: POST
Request URI:  https://blablabla
Proxy:      <none>
Request params: <none>
Query params: <none>
Form params:  <none>
Path params:  <none>
Headers:    HeaderA=....
        HeaderB=.....
Cookies:    <none>
Multiparts:   <none>
Body:
{
    "body":"body"
}
```

executed successfully.

------------

Logs output for a case with custom Content-Length header:

```
Request method: POST
Request URI:  https://blablabla
Proxy:      <none>
Request params: <none>
Query params: <none>
Form params:  <none>
Path params:  <none>
Headers:    HeaderA=....
        HeaderB=.....
        Content-Length=98
Cookies:    <none>
Multiparts:   <none>
Body:
{
    "body":"body"
}
```

fails with exception
org.apache.http.client.ClientProtocolException
  at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:839)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
  at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
  at io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:2072)
  at io.restassured.internal.http.HTTPBuilder.post(HTTPBuilder.java:350)
  at io.restassured.internal.http.HTTPBuilder$post$2.call(Unknown Source)
  at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1183)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)
  at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
  at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
  at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)
  at io.restassured.filter.Filter$filter$0.call(Unknown Source)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
  at io.restassured.filter.Filter$filter.call(Unknown Source)
  at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
  at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)
  at io.restassured.filter.Filter$filter.call(Unknown Source)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
  at io.restassured.filter.Filter$filter.call(Unknown Source)
  at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
  at io.qameta.allure.restassured.AllureRestAssured.filter(AllureRestAssured.java:107)
  at io.restassured.filter.Filter$filter.call(Unknown Source)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
  at io.restassured.filter.Filter$filter.call(Unknown Source)
  at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
  at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:140)
  at io.restassured.filter.Filter$filter.call(Unknown Source)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
  at io.restassured.filter.Filter$filter.call(Unknown Source)
  at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
  at io.restassured.filter.Filter$filter.call(Unknown Source)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
  at io.restassured.filter.Filter$filter$0.call(Unknown Source)
  at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
  at io.restassured.filter.FilterContext$next.call(Unknown Source)
  at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1672)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)
  at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
  at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
  at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
  at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1678)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)
  at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
  at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
  at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
  at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:177)
  at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)
  at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
  at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
  at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
  at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:261)
  at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
  at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
  at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
  at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
  at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
  at org.testng.TestRunner.privateRun(TestRunner.java:764)
  at org.testng.TestRunner.run(TestRunner.java:585)
  at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  at org.testng.SuiteRunner.run(SuiteRunner.java:286)
  at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
  at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  at org.testng.TestNG.runSuites(TestNG.java:1069)
  at org.testng.TestNG.run(TestNG.java:1037)
  at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: org.apache.http.ProtocolException: Content-Length header already present
  at org.apache.http.protocol.RequestContent.process(RequestContent.java:97)
  at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
  at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:167)
  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:484)
  at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
  ... 121 more

any ideas for a fix or eventual workaround are highly appreciated. 
and no, I cannot drop this header, we need to test it intentionally.

**Comment by johanhaleby** [comment]
Sounds reasonable that if you define the content-length header yourself then RA should override it. Maybe you could try to provide a pull request? That would be really helpful.

**Comment by JeremiahDo** [comment]
Please fix it. The exact thing happening to me but with version 4.5.1
