### ISSUE TITLE
[4.5.1] java.lang.NoSuchMethodError on basic test since 4.5

### ISSUE THREAD

**Issue by frayien** [rest-assured/rest-assured#1550]
Hi,

I recently updated my project from 4.4.0 to 4.5.1 and now I get a `java.lang.NoSuchMethodError`, the exact error is :
```
java.lang.NoSuchMethodError: 'void io.restassured.internal.RequestSpecificationImpl.<init>(java.lang.String, int, java.lang.String, io.restassured.authentication.AuthenticationScheme, java.util.List, io.restassured.specification.RequestSpecification, boolean, io.restassured.config.RestAssuredConfig, io.restassured.internal.log.LogRepository, io.restassured.specification.ProxySpecification, boolean)'
```
full log from `.\gradlew test --debug` at : [debug.txt](https://github.com/rest-assured/rest-assured/files/8062774/debug.txt)
full stack trace : (prefix `2022-02-14T12:23:17.923-0500 [DEBUG] [TestEventLogger]` eluded for readability)
```
 TestControllerTests > normalAll() FAILED
     java.lang.NoSuchMethodError: 'void io.restassured.internal.RequestSpecificationImpl.<init>(java.lang.String, int, java.lang.String, io.restassured.authentication.AuthenticationScheme, java.util.List, io.restassured.specification.RequestSpecification, boolean, io.restassured.config.RestAssuredConfig, io.restassured.internal.log.LogRepository, io.restassured.specification.ProxySpecification, boolean)'
         at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.logRequestIfApplicable(MockMvcRequestSenderImpl.java:456)
         at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.sendRequest(MockMvcRequestSenderImpl.java:433)
         at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.get(MockMvcRequestSenderImpl.java:476)
         at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.get(MockMvcRequestSenderImpl.java:81)
         at fr.frayien.test.controller.TestControllerTests.normalAll(TestControllerTests.java:52)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
         at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
         at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
         at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
         at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
         at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
         at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
         at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
         at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
         at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
         at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
         at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
         at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
         at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
         at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
         at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
         at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
         at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
         at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
         at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
         at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
         at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
         at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
         at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
         at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
         at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
         at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
         at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
         at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
         at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
         at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
         at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

I simplified my project to :
build.gradle
```gradle
plugins {
	id 'org.springframework.boot' version '2.5.9'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
}

group = 'fr.frayien'
version = '1.0.0'
sourceCompatibility = '11'
targetCompatibility = '11'


repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web:2.5.9'
	testImplementation 'org.springframework.boot:spring-boot-starter-test:2.5.9'


	testImplementation 'io.rest-assured:spring-mock-mvc:4.5.1'
	testImplementation 'org.mockito:mockito-core:3.12.4'
}

test {
	useJUnitPlatform()
}
```

src/main/java/fr/frayien/test/TestApplication.java
```java
package fr.frayien.test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class TestApplication {

	public static void main(String[] args) {
		SpringApplication.run(TestApplication.class, args);
	}

}
```

src/main/java/fr/frayien/test/controller/TestController.java
```java
package fr.frayien.test.controller;

import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class TestController {

    @GetMapping("/api/test")
    @ResponseStatus(HttpStatus.OK)
    List<Integer> list() {
        return List.of(1,2,3);
    }
}
```

src/test/java/fr/frayien/test/controller/TestControllerTests.java
```java
package fr.frayien.test.controller;


import static io.restassured.module.mockmvc.RestAssuredMockMvc.given;

import org.hamcrest.Matchers;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpStatus;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

import io.restassured.module.mockmvc.RestAssuredMockMvc;

@EnableWebMvc
@WebAppConfiguration
@SpringBootTest
public class TestControllerTests {

    
    @Autowired
	@InjectMocks
	TestController controller;

	AutoCloseable closeable;

	@BeforeEach
	void setUp() {
		closeable = MockitoAnnotations.openMocks(this);
		RestAssuredMockMvc.standaloneSetup(MockMvcBuilders.standaloneSetup(controller));
		RestAssuredMockMvc.enableLoggingOfRequestAndResponseIfValidationFails();
	}

	@AfterEach
	void close() {
		try {
			closeable.close();
		} catch (Exception e) { }
	}

	@Test
	void normalAll() {

		given()
			.when()
			.get("/api/test")
			.then()
			.status(HttpStatus.OK)
            .body("[0]",        Matchers.equalTo(1))
            .body("[1]",        Matchers.equalTo(2))
            .body("[2]",        Matchers.equalTo(3))
            .body("[3]", Matchers.nullValue());
	}
}
```

If I switch back to 4.4.0 there is no error. Am I doing something wrong ?

**Comment by johanhaleby** [comment]
Could you be depending on an unsupported groovy version?

**Comment by PasupuletiRohini** [comment]
Is this issue resolved? I am facing the same issue when I use the rest-assured version from 4.5.1.
The transitive groovy dependencies from rest-assured contain version 4.0.1. 
 Please help me to solve the issue.

**Comment by frayien** [comment]
> Is this issue resolved? I am facing the same issue when I use the rest-assured version from 4.5.1.

I checked the code base and we still use 4.4.0
```gradle
testImplementation 'io.rest-assured:spring-mock-mvc:4.4.0'
```
So I guess I did not find a solution and went back to the previous version...
