### ISSUE TITLE
No able to create API request with Mime Type 

### ISSUE THREAD

**Issue by AbhishekDeshpande1** [rest-assured/rest-assured#1584]
While creating post call with multi part for PDF file i am getting below error -

groovy.lang.MissingMethodException: No signature of method: org.apache.http.entity.mime.MultipartEntityBuilder.setMimeSubtype() is applicable for argument types: (String) values: [form-data]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.multipart.RestAssuredMultiPartEntity.<init>(RestAssuredMultiPartEntity.groovy:50)

**Comment by 19niki** [comment]
I was getting the same error, I have put this below jar in my pom.xml and it worked for me.

dependency>
	<groupId>org.apache.httpcomponents</groupId>
	<artifactId>httpmime</artifactId>
	<version>4.5.9</version>
</dependency>
