### ISSUE TITLE
Compile failed: unsupported Target MODULE

### ISSUE THREAD

**Issue by lucas-nguyen-17** [rest-assured/rest-assured#1626]
I tried to built RA with latest commit, but failed. My command is `mvn clean compile`

```
[INFO] Reactor Summary for REST Assured Parent POM 5.2.1-SNAPSHOT:
[INFO]
[INFO] REST Assured Parent POM ............................ SUCCESS [  0.259 s]
[INFO] REST Assured Modules ............................... SUCCESS [  0.006 s]
[INFO] json-schema-validator .............................. SUCCESS [  1.344 s]
[INFO] rest-assured-common ................................ SUCCESS [  1.960 s]
[INFO] json-path .......................................... SUCCESS [  1.674 s]
[INFO] xml-path ........................................... FAILURE [  2.049 s]
[INFO] REST Assured ....................................... SKIPPED
[INFO] spring-commons ..................................... SKIPPED
[INFO] spring-mock-mvc .................................... SKIPPED
[INFO] Scala Support ...................................... SKIPPED
[INFO] spring-web-test-client ............................. SKIPPED
[INFO] kotlin-extensions .................................. SKIPPED
[INFO] spring-mock-mvc-kotlin-extensions .................. SKIPPED
[INFO] rest-assured-all ................................... SKIPPED
[INFO] REST Assured Examples .............................. SKIPPED
[INFO] Scalatra Example ................................... SKIPPED
[INFO] Scalatra REST service example ...................... SKIPPED
[INFO] REST Assured Java integration tests ................ SKIPPED
[INFO] Spring MVC example ................................. SKIPPED
[INFO] Scala Example ...................................... SKIPPED
[INFO] Scala Spring Mock MVC Example ...................... SKIPPED
[INFO] Kotlin Example ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.390 s
[INFO] Finished at: 2022-09-26T17:14:37+07:00
[INFO] ------------------------------------------------------------------------

---------------------------------------------------
Exception in thread "main" BUG! exception in phase 'class generation' in source unit '/C:/Users/dunguyen/IdeaProjects/rest-assured/xml-path/src/main/groovy/io/restassured/internal/path/xml/mapping/XmlPathJakartaEEObjectDeserializer.groovy' unsuppor
ted Target MODULE
        at org.codehaus.groovy.vmplugin.v5.Java5.getElementCode(Java5.java:307)
        at org.codehaus.groovy.vmplugin.v5.Java5.configureAnnotationFromDefinition(Java5.java:204)
        at org.codehaus.groovy.vmplugin.v5.Java5.configureAnnotation(Java5.java:214)
        at org.codehaus.groovy.classgen.AnnotationVisitor.visit(AnnotationVisitor.java:81)
        at org.codehaus.groovy.classgen.ExtendedVerifier.visitAnnotation(ExtendedVerifier.java:151)
        at org.codehaus.groovy.classgen.ExtendedVerifier.visitAnnotations(ExtendedVerifier.java:112)
        at org.codehaus.groovy.classgen.ExtendedVerifier.visitConstructorOrMethod(ExtendedVerifier.java:73)
        at org.codehaus.groovy.classgen.ExtendedVerifier.visitMethod(ExtendedVerifier.java:69)
        at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1056)
        at org.codehaus.groovy.classgen.ExtendedVerifier.visitClass(ExtendedVerifier.java:57)
        at org.codehaus.groovy.control.CompilationUnit$14.call(CompilationUnit.java:762)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1024)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:562)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:540)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:517)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:496)
        at org.codehaus.gmaven.runtime.v2_0.ClassCompilerFeature$ClassCompilerImpl.compile(ClassCompilerFeature.java:153)
        at org.codehaus.gmaven.plugin.compile.AbstractCompileMojo.compile(AbstractCompileMojo.java:211)
        at org.codehaus.gmaven.plugin.compile.AbstractCompileMojo.process(AbstractCompileMojo.java:175)
        at org.codehaus.gmaven.plugin.ComponentMojoSupport.doExecute(ComponentMojoSupport.java:60)
        at org.codehaus.gmaven.plugin.MojoSupport.execute(MojoSupport.java:71)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```
I can compile successfully with commit `004a4b63` before upgrading to groovy 4. Did I miss anything?

**Comment by JanMosigItemis** [comment]
Seems like the gmaven compiler dependencies etc. are a bit outdated. It compiles fine with JDK 8. Note that the tests are using some sort of non platform independent path mangling, so they won't work on Windows it seems.

I successfully compiled the repo with `JAVA_HOME=/your/path/to/jdk8 mvn clean install -DskipTests=true`
