### ISSUE TITLE
io.restassured.config.ObjectMapperConfig.newJakartaEEObjectMapperFactoryOrNullIfNotInClasspath

### ISSUE THREAD

**Issue by ShantiBabu** [rest-assured/rest-assured#1672]
Hi - I am using Rest Assured 5.1.1. Also tried with 4.2.0, 5.20 as well.  I am getting this error java.lang.NoSuchMethodError: 'boolean io.restassured.common.mapper.resolver.ObjectMapperResolver.isJakartaEEInClassPath()'
	at io.restassured.config.ObjectMapperConfig.newJakartaEEObjectMapperFactoryOrNullIfNotInClasspath(ObjectMapperConfig.java:265)
	at io.restassured.config.ObjectMapperConfig.<init>(ObjectMapperConfig.java:60)
	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:422)

Appreciate your help.

**Comment by davletshinruslan9** [comment]
I am getting the same issue. I am using Rest Assured 5.4.0. I tried to add json-path and xml-path Maven dependencies with the same version 5.4.0 but no luck. I am getting the error on the line where given().header() method is. Any recommendation is appreciated.

**Comment by davletshinruslan9** [comment]
UPDATE: Got my issue resolved by adding the below dependency without removing the rest-assured dependency:
```
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured-all</artifactId>
    <version>5.4.0</version>
    <scope>test</scope>
</dependency>
```
