### ISSUE TITLE
GroovyCastException: InternalHttpClient to AbstractHttpClient

### ISSUE THREAD

**Issue by JanMosigItemis** [rest-assured/rest-assured#1676]
Hi there,

I am trying to set custom timeouts for my rest-assured tests like this:

```
final var requestConfig = RequestConfig.custom()
        .setConnectTimeout(10000)
        .setConnectionRequestTimeout(10000)
        .setSocketTimeout(10000)
        .build();

    final var httpClientConfig = HttpClientConfig.httpClientConfig()
        .httpClientFactory(() -> HttpClientBuilder.create().setDefaultRequestConfig(requestConfig).build());

    final var config = RestAssured.config().httpClient(httpClientConfig);
    RestAssured.given().config(config)...
```
When I run this code, I get:

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.apache.http.impl.client.InternalHttpClient@261db982' with class 'org.apache.http.impl.client.InternalHttpClient' to class 'org.apache.http.impl.client.AbstractHttpClient'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:421)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:332)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:252)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:621)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1703)
```

which imo is due to https://github.com/rest-assured/rest-assured/blob/69576e40485c452be05a118a6b4271857d86fb21/rest-assured/src/main/groovy/io/restassured/internal/RequestSpecificationImpl.groovy#L125

Apache's HttpClientBuilder creates an instance of CloseableHttpClient which is not type compatible with AbstractHttpClient

Using RestAssured 5.3.0 here.

Is there a way to fix this? Any help would be appreciated.

**Comment by lucas-nguyen-17** [comment]
This is a known issue of Rest-Assured. The author is too busy to fix this. Could you propose a pull request?
