### ISSUE TITLE
Update to httpclient 5

### ISSUE THREAD

**Issue by hazendaz** [rest-assured/rest-assured#1696]
The upgrade is rather trivial and is java 8 compliant.  It would be nice for this to be upgraded.  I can do the work if needed.

**Comment by gruenich** [comment]
Probably having a merge requests increases the chances of getting this change including by the author of REST-assured.

**Comment by hazendaz** [comment]
I'll see what I can do when I get some time.  I have a few weeks here around holiday's that I might give it a shot.  I just forked the repo and will see what I can do.

**Comment by tprus** [comment]
+1

**Comment by formatq** [comment]
+1

**Comment by apupier** [comment]
note that with a mix with HttpClient 5.6 on our side, we are hitting an issue as the [gzip format has been "cleaned"](https://issues.apache.org/jira/browse/HTTPCLIENT-2409?focusedCommentId=18047208&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18047208) and this project is not looking to the real contentype/contentencoding to decide if it is a gzip content or not

```
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at io.restassured.internal.http.GZIPEncoding$GZIPDecompressingEntity.getContent(GZIPEncoding.java:72)
	at org.apache.http.conn.BasicManagedEntity.getContent(BasicManagedEntity.java:85)
	at io.restassured.internal.http.HTTPBuilder.parseResponse(HTTPBuilder.java:554)
	at io.restassured.internal.RestAssuredHttpBuilder.parseResponse(RestAssuredHttpBuilder.java:228)
	at io.restassured.internal.RestAssuredHttpBuilder.doRequest(RestAssuredHttpBuilder.java:158)
```

for reference:
https://issues.apache.org/jira/browse/HTTPCLIENT-2409?focusedCommentId=18047208&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18047208
https://issues.apache.org/jira/browse/CAMEL-23366
