### ISSUE TITLE
Error java.lang.NoSuchMethodError ParamConfig.<init>

### ISSUE THREAD

**Issue by PavlosSiempos** [rest-assured/rest-assured#1732]
When upgraded to spring boot version 3.1.1 and rest assured version 5.3.2, running the tests i am getting the following error 

java.lang.NoSuchMethodError: 'void io.restassured.config.ParamConfig.<init>(io.restassured.config.ParamConfig$UpdateStrategy, io.restassured.config.ParamConfig$UpdateStrategy, io.restassured.config.ParamConfig$UpdateStrategy)'

	at io.restassured.module.spring.commons.config.ConfigConverter.toParamConfig(ConfigConverter.java:35)
	at io.restassured.module.spring.commons.config.ConfigConverter.convertToRestAssuredConfig(ConfigConverter.java:29)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.performRequest(MockMvcRequestSenderImpl.java:244)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.sendRequest(MockMvcRequestSenderImpl.java:478)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.post(MockMvcRequestSenderImpl.java:535)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.post(MockMvcRequestSenderImpl.java:85)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSpecificationImpl.post(MockMvcRequestSpecificationImpl.java:595)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSpecificationImpl.post(MockMvcRequestSpecificationImpl.java:65)

Is there any incompatibility with the spring commons that contain the ParamConfig constructor ? I explicitly declared also spring  commons 4.5.1 which seems to be the compatible version with spring boot 3.1.1 but i get the same error .

**Comment by IefCuynen** [comment]
@PavlosSiempos 
I bumped into the same issue with Spring boot  3.1.3 and rest assured 5.4.0.
I did solve it by upgrading to the latest version of Spring boot - 3.2.1
I hope it helps for you as well.
