### ISSUE TITLE
Random NPEs parsing JSON in responses

### ISSUE THREAD

**Issue by artazar** [rest-assured/rest-assured#1736]
The issue:
----------
While executing API test bundles based on Rest Assured via Jenkins as CI system, we observe absolutely random test failures that point to inability to parse JSON messages. "Randomly" here means it may happen 1 time out of 30 runs (so once in 2 weeks), but we as well observed 2 failures within same day (that makes it approximately 1 out of 5 runs). 

The faulty pattern normally points to JsonPath unable to obtain results (getting null):
```
    at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
    at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
    at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
    at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
    at utility.Utility.registerUserIfNotExist(Utility.java:505)
```
When tests are launched again immediately afterwards, the issue does not reoccur. The build agents are ephemeral (k8s pods), so each new run is a completely clean system.

By logging the JSON responses obtained by HTTP client, we clearly see received data and well-formed JSON messages. 
```
  JsonPath jsonPathEvaluator = response.jsonPath();
  log.info("Response as JSONPath: " + jsonPathEvaluator.prettify());      <------ here we log the data content successfully
  String verificationId = jsonPathEvaluator.get("data.verification_id");  <------ here we get an exception
```
They are logged right before the exception. Yet for some reason JsonPath.get() function reports it as null.
```
Response as JSONPath: {
    "data": {
        "verification_id": "xxxxxx",
        "session_info": "xxxxxx"
    },
    "meta_data": {
        "code": 201,
        "message": "xxxxxx"
    }
}
```

Since it has been confirmed that received data packets are absolutely valid, I see this as some random bug inside rest-assured libraries that I cannot find explanation for. 

It's worth noting that tests are executed with concurrency in 20 threads. 

Is there any help you can provide? Or any ideas what may cause such effects?

Similar issues:
--------------
Two github issues are particularly similar in their symptoms to what I observe.
Two of them are particularly similar and talk about NPE's in jsonPath while running tests:
[Not able to read the response through Json Path, Getting null pointer exception · Issue #1295 · rest-assured/rest-assured](https://github.com/rest-assured/rest-assured/issues/1295) 
[JsonPath not working within test scopes in AdoptOpenJDK 11-j9, 12-j9 · Issue #1307 · rest-assured/rest-assured](https://github.com/rest-assured/rest-assured/issues/1307) 
But they are both from year 2020, so pretty outdated.

Things already tried:
--------------------
1) Update io.rest-assured to the most recent version.
2) Update JDK from 11 to 17 on the Jenkins agent executing the tests (this helped to make exceptions cleaner btw).
3) Updated Jenkins packages/plugins/etc to most recent versions.
4) Never reproduced when tests are executed at local laptop.

Logs:
-----
Full exception trace:
```
BUG! exception in phase 'class generation' in source unit 'Script1.groovy' unexpected NullPointerException
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:943)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:572)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:585)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:597)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:459)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:495)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:469)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:186)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:75)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at io.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:84)
        at io.restassured.internal.path.json.JSONAssertion.this$2$eval(JSONAssertion.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
        at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
        at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
        at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
        at io.restassured.path.json.JsonPath.get(JsonPath.java:203)
        at utility.Utility.registerUserIfNotExist(Utility.java:505)
        at com.pulse.tests.TrackTests.verifyAddDeleteTrackFromPlaylist(TrackTests.java:250)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "this.listKeys[i]" is null
        at org.codehaus.groovy.util.ListHashMap.get(ListHashMap.java:120)
        at org.codehaus.groovy.ast.NodeMetaDataHandler.getNodeMetaData(NodeMetaDataHandler.java:44)
        at org.codehaus.groovy.ast.ClassHelper.isDynamicTyped(ClassHelper.java:433)
        at org.codehaus.groovy.ast.MethodNode.setReturnType(MethodNode.java:154)
        at org.codehaus.groovy.ast.MethodNode.<init>(MethodNode.java:70)
        at org.codehaus.groovy.ast.ClassNode.addMethod(ClassNode.java:658)
        at org.codehaus.groovy.ast.ClassNode.addSyntheticMethod(ClassNode.java:681)
        at org.codehaus.groovy.classgen.Verifier.addGetLookupMethod(Verifier.java:445)
        at org.codehaus.groovy.classgen.Verifier.visitClass(Verifier.java:261)
        at org.codehaus.groovy.control.CompilationUnit$3.call(CompilationUnit.java:755)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:938)
        ... 52 more
```

One more kind of exception that does NOT involve JsonPath, but still fails on parsing JSON response:

```
BUG! exception in phase 'class generation' in source unit 'Script1.groovy' unexpected NullPointerException
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:943)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:572)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:585)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:597)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:459)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:495)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:469)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:186)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:75)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at io.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:84)
        at io.restassured.internal.path.json.JSONAssertion.this$2$eval(JSONAssertion.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
        at io.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
        at io.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
        at io.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
        at io.restassured.internal.assertion.BodyMatcher.validate(BodyMatcher.java:102)
        at io.restassured.internal.assertion.BodyMatcherGroup.lambda$validate$0(BodyMatcherGroup.java:30)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at io.restassured.internal.assertion.BodyMatcherGroup.validate(BodyMatcherGroup.java:30)
        at io.restassured.internal.assertion.BodyMatcherGroup$validate$9.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at io.restassured.internal.assertion.BodyMatcherGroup$validate$9.call(Unknown Source)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:499)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$13.call(Unknown Source)
        at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
        at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:270)
        at io.restassured.specification.ResponseSpecification$body$16.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:212)
        at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:117)
        at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
        at com.pulse.tests.AuthServiceEmailValidationTests.VerifyOtpEmailInvalidOTP(AuthServiceEmailValidationTests.java:156)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "this.listKeys[i]" is null
        at org.codehaus.groovy.util.ListHashMap.get(ListHashMap.java:120)
        at org.codehaus.groovy.ast.NodeMetaDataHandler.getNodeMetaData(NodeMetaDataHandler.java:44)
        at org.codehaus.groovy.ast.ClassHelper.isDynamicTyped(ClassHelper.java:433)
        at org.codehaus.groovy.ast.MethodNode.setReturnType(MethodNode.java:154)
        at org.codehaus.groovy.ast.MethodNode.<init>(MethodNode.java:70)
        at org.codehaus.groovy.ast.ClassNode.addMethod(ClassNode.java:658)
        at org.codehaus.groovy.ast.ClassNode.addSyntheticMethod(ClassNode.java:681)
        at org.codehaus.groovy.classgen.Verifier.addGetLookupMethod(Verifier.java:445)
        at org.codehaus.groovy.classgen.Verifier.visitClass(Verifier.java:261)
        at org.codehaus.groovy.control.CompilationUnit$3.call(CompilationUnit.java:755)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:938)
        ... 84 more
```

Involved packages:
-------------------
io.rest-assured 5.3.1
org.json 20230227
org.apache.logging.log4j 2.20.0

Attached files:
--------------
[pom.xml.zip](https://github.com/rest-assured/rest-assured/files/12761932/pom.xml.zip)

**Comment by artazar** [comment]
Some extra details to add:
1) After switching the test run mode to single-threaded, the issue has not reoccurred. But given the randomness of it, it may as well be that too little time has passed (1 week).
2) Also checked running this in a different CI system (Azure Devops), and hit these exceptions there too.

**Comment by mletynski** [comment]
We have exactly same issue, its not thread safe. Any info when this can be fixed ?

**Comment by artazar** [comment]
Looks like it is going to be addressed in Groovy v5:

https://issues.apache.org/jira/browse/GROOVY-10861

https://github.com/apache/groovy/commit/6953697ca27d69bf03271c83cd22348dfc58ea5f

**Comment by vitalii-shemetov** [comment]
The same problem. We use rest assured with parallel execution. It's some random bug.
Any ideas how to solve it ?
