### ISSUE TITLE
Error java.lang.NoSuchMethodError for HttpMethod.resolve().

### ISSUE THREAD

**Issue by userMuratt** [rest-assured/rest-assured#1760]
When upgrading my project to Spring Boot 3.2.1, I get the following error:

`'org.springframework.http.HttpMethod org.springframework.http.HttpMethod.resolve(java.lang.String)'
java.lang.NoSuchMethodError: 'org.springframework.http.HttpMethod org.springframework.http.HttpMethod.resolve(java.lang.String)'
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.toValidHttpMethod(MockMvcRequestSenderImpl.java:855)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.request(MockMvcRequestSenderImpl.java:805)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.request(MockMvcRequestSenderImpl.java:801)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.request(MockMvcRequestSenderImpl.java:105)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSpecificationImpl.request(MockMvcRequestSpecificationImpl.java:759)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSpecificationImpl.request(MockMvcRequestSpecificationImpl.java:65)`
	
HttpMethod.resolve() is used with Spring-web 6.0.15 at the latest: https://docs.spring.io/spring-framework/docs/6.0.15/javadoc-api/org/springframework/http/HttpMethod.html.

What is the recommended way?

**Comment by a-s-rose** [comment]
Same for me here, too. Seems the actual version of rest-assured is not fully compatible with spring 6.x.

**Comment by felhag** [comment]
Any updates on this? Created a similar pull request to fix WebTestClientRequestSenderImpl:

https://github.com/rest-assured/rest-assured/pull/1778
