### ISSUE TITLE
Cannot set multipart mime-type to a value with semi-colons in it

### ISSUE THREAD

**Issue by jagregory** [rest-assured/rest-assured#1774]
Calling multiPart with a mime-type that has a parameter, which is a valid mime-type, results in an error:

```kotlin
.multiPart("file", "{}", "application/vnd.test;version=1")
```

Error:
```
MIME type may not contain reserved characters
	at org.apache.http.util.Args.check(Args.java:36)
	at org.apache.http.entity.ContentType.create(ContentType.java:229)
	at org.apache.http.entity.mime.content.StringBody.<init>(StringBody.java:113)
```

The `org.apache.http.entity.ContentType.create` function does not permit values with parameters, you need to use the `ContentType.parse` function instead, but there's no way (that I can see) in rest-assured to pass your own `ContentType` instance, only strings.

**Comment by Jotschi** [comment]
I also  encountered this issue. The W3C even has an example in its docs:

```
  --simple boundary 
     Content-type: text/plain; charset=us-ascii 
```
https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html#:~:text=linebreak.%20%0A%20%20%20%20%20%2D%2Dsimple%20boundary-,Content%2Dtype%3A%20text/plain%3B%20charset%3Dus%2Dascii,-This%20is%20explicitly

The curious thing is that .multiPart("test", 42) will result in a part that has `Content-type: text/plain; charset=us-ascii` in the part.

Another curious thing is that quarkus-rest seems to fail for those parts aswell (when handled on the serverside)
But that's an issue for a different repo.
