### ISSUE TITLE
Unsupported cookie spec: ignoreCookies

### ISSUE THREAD

**Issue by johanhaleby** [rest-assured/rest-assured#542]
_From [dev.inn...@gmail.com](https://code.google.com/u/108506579882497347800/) on February 27, 2015 17:11:33_

What steps will reproduce the problem? 1. Write a simple case, say testing 404
@Test
    public void testStatusNotFound() {
        given().log().all().with().authentication().basic("Blah","BlahhalB").
        expect().statusCode(404).when().
        get("/notfound");
    }

baseURI is already set. My service is up and running
1. Run this in Eclipse as JUnit test
2. Get the following exception :- java.lang.IllegalStateException: Unsupported cookie spec: ignoreCookies.

Full stacktrace attached. Below is just an excerpt : 

java.lang.IllegalStateException: Unsupported cookie spec: ignoreCookies
    at org.apache.http.cookie.CookieSpecRegistry.getCookieSpec(CookieSpecRegistry.java:114)
    at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:168) What version of the product are you using? On what operating system? rest-assured 2.4.0 /Windows 8.1 /Eclipse Kepler with Maven/ Tomcat 8.0.15/ Jersey Please provide any additional information below. I get the same exception with POST as well, and also when I disable basic auth.

**Attachment:** [RestAssuredCookieIssue.txt](http://code.google.com/p/rest-assured/issues/detail?id=387)

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=387_

**Comment by paul-hammant** [comment]
If anyone is still looking for causes for this check to see if you have clashing versions of org.apache.http.* in your classpath. I shaded something upstream of me (I forked that upstream thing) and everything went back to working (tests pass) again.
