### ISSUE TITLE
Random NPE with RestAssured.enableLoggingOfRequestAndResponseIfValidationFails()

### ISSUE THREAD

**Issue by rakus** [rest-assured/rest-assured#652]
During our tests we see random NPE if enableLoggingOfRequestAndResponseIfValidationFails is enabled.
- rest-assured 2.8.0
- Java 7 (ibm-java)
- Test are ran via Maven surefire
- Entire Testsuite does around 2200 REST request
- Out of 34 runs 20 fail with NPE
- The exception occures in the middle of a series of requests, that all get the same response (same headers, same body). I verified that using a tcp-monitor.

I've seen the following Exceptions:

```
java.lang.NullPointerException
        at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.$getCallSiteArray(RestAssuredResponseOptionsGroovyImpl.groovy)
        at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.headers(RestAssuredResponseOptionsGroovyImpl.groovy)
        at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.getHeaders(RestAssuredResponseOptionsGroovyImpl.groovy:277)
        at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.getHeaders(RestAssuredResponseOptionsImpl.java:249)
        at com.jayway.restassured.builder.ResponseBuilder.clone(ResponseBuilder.java:68)
        at com.jayway.restassured.filter.log.StatusCodeBasedLoggingFilter.cloneResponseIfNeeded(StatusCodeBasedLoggingFilter.java:116)
        at com.jayway.restassured.filter.log.StatusCodeBasedLoggingFilter.filter(StatusCodeBasedLoggingFilter.java:104)
        at com.jayway.restassured.filter.log.ResponseLoggingFilter.filter(ResponseLoggingFilter.java:31)
        at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
        at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:73)
        at com.jayway.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:101)
        at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at com.jayway.restassured.filter.Filter$filter$0.call(Unknown Source)
        at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:73)
        at com.jayway.restassured.filter.FilterContext$next.call(Unknown Source)
        at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1574)
        at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
        at java.lang.reflect.Method.invoke(Method.java:620)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
        at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
        at com.jayway.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:163)
        at com.jayway.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
    at ... custom test class
```

and

```
java.lang.NullPointerException
    at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToBoolean(DefaultTypeTransformation.java)
    at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.booleanUnbox(DefaultTypeTransformation.java:74)
    at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.headers(RestAssuredResponseOptionsGroovyImpl.groovy:273)
    at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.getHeaders(RestAssuredResponseOptionsGroovyImpl.groovy:277)
    at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.getHeaders(RestAssuredResponseOptionsImpl.java:249)
    at com.jayway.restassured.builder.ResponseBuilder.clone(ResponseBuilder.java:68)
    at ... like above
```

EDIT: 
- This is rest-assured 2.8.0 runing with java7 (ibm-java).
- Cannot reproduce the problem in the debugger

**Comment by johanhaleby** [comment]
Do you have a code example of how you enable "enableLoggingOfRequestAndResponseIfValidationFails"?

**Comment by johanhaleby** [comment]
Is this still a problem with the 2.9.0 release?
