### ISSUE TITLE
rest-assured: Request timeouts

### ISSUE THREAD

**Issue by manoj7shekhawat** [rest-assured/rest-assured#713]
Hi,

I'm using 
`testCompile('com.jayway.restassured:rest-assured:2.4.0')`

And my request stuck at:
```
Response response = given().relaxedHTTPSValidation()
.spec(requestSpecBuilder.build()).body(createBody()).when().post("/some/version/api").thenReturn();
```

Eventually TestNG timeouts with below error stack:
```
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.executeResources() didn't finish within the time-out 420000
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
	at com.jayway.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:31)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:49)
	at com.jayway.restassured.filter.FilterContext$next.call(Unknown Source)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeFilterChain(RequestSpecificationImpl.groovy:956)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1414)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy)
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.jayway.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:154)
	at com.jayway.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
	at oracle.idaas.oauth.endpoint.Token.generateAccessToken(Token.java:100)
	at oracle.idaas.oauth.tasks.AccessTokenMain.generateTokensWithoutUsers(AccessTokenMain.java:125)
	at oracle.idaas.oauth.tasks.AccessTokenMain.reGenerateAccessTokens(AccessTokenMain.java:77)
	at oracle.idaas.idpsRest.provider.HttpAccess.refreshAccessTokens(HttpAccess.java:1036)
	at oracle.idaas.idpsRest.provider.HttpAccess.GETservice(HttpAccess.java:393)
	at oracle.idaas.idpsRest.testProviders.CommonResourcesREST.LISTresource(CommonResourcesREST.java:2658)
	at oracle.idaas.idpsRest.testProviders.CommonResourcesREST.executeREST(CommonResourcesREST.java:152)
	at oracle.idaas.idpsRest.testProviders.CommonResources.executeOperations(CommonResources.java:240)
	at oracle.idaas.idpsRest.testProviders.RestResources.executeResources(RestResources.java:179)
	at sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Both HttpAccess.java and Token.java classes have same rest-assured config in them as:
```
static {
		RestAssured.config =
				newConfig().httpClient(httpClientConfig().httpClientFactory(new HttpClientConfig.HttpClientFactory() {
					DefaultHttpClient client = new DefaultHttpClient();
					ClientConnectionManager mgr = client.getConnectionManager();
					HttpParams params = client.getParams();

					@Override
					public HttpClient createHttpClient() {
						HttpClient client = new DefaultHttpClient(
								new ThreadSafeClientConnManager(params, mgr.getSchemeRegistry()), params);
						return client;
					}
				}).reuseHttpClientInstance());
	} 
```

After this timeout exception, all next calls to any REST API via HttpAccess.java class stuck and eventually TestNG timeouts all those requests.
 
I'm not sure if this is a bug in my code or rest-assured library issue. Can somebody confirm this.

**Comment by manoj7shekhawat** [comment]
Most probably it's due to my bad code, where I am creating a deadlock.

I'm updating my code and will again run my tests. If refactoring code solves this issue, then I'll close this bug.

**Comment by johanhaleby** [comment]
Yes you should use 3.0.0, and I don't think that your issue has anything to do with RA but it would be nice of you to verify.

**Comment by manoj7shekhawat** [comment]
Yup indeed it was my bad code. Updated to 3.0.0 and refracting code solved it.
