### ISSUE TITLE
NoSuchMethodError: org.apache.http.entity.ContentType.withParameters problem (revisiting)

### ISSUE THREAD

**Issue by ironsideshu** [rest-assured/rest-assured#718]
I've been receiving this message that I'm sure others have seen

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.http.entity.ContentType.withParameters([Lorg/apache/http/NameValuePair;)Lorg/apache/http/entity/ContentType;
	at org.apache.http.entity.mime.MultipartEntityBuilder.buildEntity(MultipartEntityBuilder.java:219)
	at org.apache.http.entity.mime.MultipartEntityBuilder.build(MultipartEntityBuilder.java:240)
	at org.apache.http.entity.mime.MultipartEntityBuilder$build$5.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)...
...
```

I'm using rest-assured (3.0.0) and hadoop-common (2.7.2) and as far as overlapping classes, I made to sure to exclude httpclient from the hadoop-common dependecy. For some reason, after packaging my program and running it (on aws emr), I continually receive the above runtime error. The main usage of rest-assured is to POST (with attachments as multiparts). 

Any idea what the problem might be? More clashing classes outside of httpclient, or maybe there is something else that I've done wrong? Btw, I'm using the Maven Shade plugin to create my fat jars.

**Comment by ivan-baranovski-intellectsoft** [comment]
I have the same problem. Any ideas?
