### ISSUE TITLE
Path param values with curly braces are interpreted as undefined path params.

### ISSUE THREAD

**Issue by yurodivuie** [rest-assured/rest-assured#739]
The following code will throw exception:

`when().get("/{id}", "{12345}");`

or 

`given().basePath("/{id}").pathParam("id","{12345}").get();1

> java.lang.IllegalArgumentException: Path parameters were not correctly defined. Undefined path parameters are: 12345.

If recursive/nested PathParams were supported, this would make sense, but the following code shows this is not the case:

`given().basePath("/{id}").pathParam("id","{12345}").pathParam("12345", "67890").get();`

> java.lang.IllegalArgumentException: Invalid number of path parameters. Expected 1, was 2. Redundant path parameters are: 12345=67890. Undefined path parameters are: 12345.

You can work around this by doing the following:

`given().urlEncodingEnabled(false).basePath("/{id}").pathParam("id", encode("{12345}", UTF_8.name())).get()`

If recursive params are not supported, then the intent of the user should be clear: param values should never be considered candidates for undefined parameters.

**Comment by robinst** [comment]
Still the case with 3.0.2 and master. I pushed a test case showing the problem: https://github.com/rest-assured/rest-assured/compare/master...robinst:issue-739-test-case

It fails with this stack trace (shortened):

```
java.lang.IllegalArgumentException: Path parameters were not correctly defined. Undefined path parameters are: bar.
	at io.restassured.internal.RequestSpecificationImpl.assertCorrectNumberOfPathParams(RequestSpecificationImpl.groovy:1336)
	at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1223)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)
	at io.restassured.filter.Filter$filter$0.call(Unknown Source)
	at io.restassured.filter.Filter$filter.call(Unknown Source)
	at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
	at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)
	at io.restassured.filter.Filter$filter.call(Unknown Source)
	at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
	at io.restassured.filter.FilterContext$next.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1722)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1728)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:168)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
	at io.restassured.itest.java.PathParamITest.supportsPassingPathParamsThatContainCurly(PathParamITest.java:59)
```

Note that there's some existing test cases for this, like this one: https://github.com/rest-assured/rest-assured/blob/master/examples/rest-assured-itest-java/src/test/java/io/restassured/itest/java/PathParamITest.java#L382

But the reason they don't fail is because they don't actually send a request, which is where the parameters are checked. Heh :).

**Comment by mauricioborges** [comment]
I think this answer here can help you: https://github.com/rest-assured/rest-assured/issues/682
