### ISSUE TITLE
Ignore "invalid header" when using rest-assured

### ISSUE THREAD

**Issue by TobiasSuhrborg** [rest-assured/rest-assured#777]
When using rest-assured we are getting an exception from the underlying (Apache) HttpClient:

```
Caused by: org.apache.http.ProtocolException: Invalid header: : 
	at org.apache.http.impl.io.AbstractMessageParser.parseHeaders(AbstractMessageParser.java:232)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:268)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:209)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	... 159 more
```

The server is sending an *invalid* header field ": " among other correct ones, which is not accepted by the used parser and throws the `ProtocolException`. Postman somehow just ignores this invalid header field. We have no chance to "fix" this invalid header field on the server side (SAP Gateway).

Is there a way to let rest-assured ignore this or implement a custom behavior?

We've tried to override `httpClientConfig().httpClientFactory()` already, but it seems to be very hard to inject a custom `MessageParser`.

Did someone maybe had a similar issue? Is it planned to use rest-assured with other HttpClients, e.g. OkHttp?

Thanks in advance.

**Comment by johanhaleby** [comment]
I'm not aware of someone else having this error. I would assume that the way to go is to configure HTTP Client along the lines you describe. I'm going to close the issue since I think that your suggested approach is probably the way to go. If you find out how to get around it please let me know and I'll consider whether it's worth adding first class support for it in RA.

**Comment by a11n** [comment]
If someone else is facing the same issue:

We worked around the issue by using some _"black magic"_ with PowerMock to replace the method implementation at runtime with our own implementation.

```java
@RunWith(PowerMockRunner.class)
@PrepareForTest(AbstractMessageParser.class)

replace(method(AbstractMessageParser.class, "parseHeaders", SessionInputBuffer.class, int.class,
       int.class, LineParser.class, List.class)).with(method(Workaround.class, "parseHeaders"));
```

In our setup we also needed to ignore some classes which caused some conflicts:
```java
@PowerMockIgnore({ "javax.net.ssl.*", "javax.security.auth.*" })
```

**Comment by johanhaleby** [comment]
hehe well that's kind of hacky but I'm glad PowerMock can be of help sometimes :)
