### ISSUE TITLE
Amazon api gateway handshake_failure issue

### ISSUE THREAD

**Issue by kmakowski** [rest-assured/rest-assured#783]
I am trying to reach rest api exposed with amazon api gateway service. I can see the correct response from this rest api when using apache httpclient 4.5.2 directly with httpclient created with this method:  HttpClientBuilder.create().build(), but when I am using http client instantiated with "new DefaultHttpClient()" snippet I see handshake_failure issue when trying to connect to amazon gateway. 

Unfortunately Rest assured is using by default "new DefaultHttpClient()" so I cannot use rest assured to connect to my rest api. I cannot even provide a manually created http client using HttpClientBuilder.create().build() because rest assured is expecting an instance extending AbstractHttpClient which is not the case for the object created with "HttpClientBuilder.create().build()" snippet.

**Comment by kmakowski** [comment]
just wanted to add that this is for rest assured v3.0.1

**Comment by johanhaleby** [comment]
Have you seen this? https://sookocheff.com/post/api/rest-assured-tests-against-api-gateway/

**Comment by kmakowski** [comment]
Yes I have seen but it did not work for me. If I understand correctly I should be able to provide my own httpclient instance with

RestAssured.config.getHttpClientConfig().httpClientFactory(() -> HttpClientBuilder.create().build());

it compiles, but in the runtime it throws an exception from a groovy (?!) file:

`Exception in thread "main" org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.apache.http.impl.client.InternalHttpClient@6f80fafe' with class 'org.apache.http.impl.client.InternalHttpClient' to class 'org.apache.http.impl.client.AbstractHttpClient'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:405)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:603)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1644)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:167)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
	at Test.main(Test.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

**Comment by kmakowski** [comment]
which looks like a bug for me

**Comment by johanhaleby** [comment]
Hmm well the error message looks like a bug but you can only supply instances of AbstractHttpClient (see [docs](https://github.com/rest-assured/rest-assured/wiki/Usage#http-client-config)). See [this](https://github.com/rest-assured/rest-assured/issues/497) issue.

**Comment by kmakowski** [comment]
oh yes, indeed this is mentioned in the docs. But still, depending on the deprecated API (org.apache.http.impl.client.DefaultHttpClient class) is a bad practice. Fixing that will be quite hard and will mean a huge rewrite of rest assured if I understand correctly :(

**Comment by johanhaleby** [comment]
That's true :(

Of course it was not deprecated when REST Assured started out and it's definitely something that I want to fix. The problem is that it'll take quite a big effort (I think) to fix it and my time is limited :(
