### ISSUE TITLE
java.lang.NoClassDefFoundError: groovy/lang/GroovyObject

### ISSUE THREAD

**Issue by PSJMcNeill** [rest-assured/rest-assured#799]
Added Rest Assured via Gradle using this: 

testCompile 'io.rest-assured:rest-assured:3.0.2'

tried a simple get to a Rest call and stored the response as a JSON.

Got the error in the title: java.lang.NoClassDefFoundError: groovy/lang/GroovyObject

Any ideas?

Read on other topics to add Groovy-All but that hasn't changed anything.

**Comment by johanhaleby** [comment]
See FAQ #2:

```gradle
testCompile (group: 'io.rest-assured', name: 'rest-assured', version:'3.0.2') {
          exclude(module: 'groovy')
}
testCompile group: 'org.codehaus.groovy', name: 'groovy-all', version:'2.4.6'
```

If this doesn't work I think you have a classpath issue with different groovy versions.

**Comment by dugsmith** [comment]
I had this error with Version 3.0.5, and with Maven, I just had to add the Groovy dependency:

```
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.12</version>
            <scope>test</scope>
        </dependency>
```

**Comment by sheetalsingh** [comment]
I am getting same error, added grovy-all in pom still issue not going

java.lang.NoClassDefFoundError: groovy/lang/GroovyObject


#maven dependency, also tried with 2.4.15 and 3.0.0-alpha-2
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>2.4.12</version>
		</dependency>

**Comment by raghuveermh30** [comment]
yeah. i have put in the first dependency but i am getting same

**Comment by manojmastiff** [comment]
I was facing the same issue surprisingly I was working with RestAssured. I struggled for one entire day to get this fixed. 

I updated maven groovy-all dependency with the latest one and this worked absolutely fine.

**Comment by pankajrachha** [comment]
Any one got the solution on the same?
Iam facing the same issue
java.lang.NoClassDefFoundError: groovy/lang/GroovyObject

**Comment by Leelaram-BB** [comment]
I'm facing this issue. Tried all solutions, no luck. Any help would be appreciated.
```
java.lang.NoClassDefFoundError: groovy/lang/GroovyObject

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:347)
	at com.bankbazaar.nanoUrlServiceTest.NanoUrlServiceBackwardTest.setup(NanoUrlServiceBackwardTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.TestRunner.beforeRun(TestRunner.java:645)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

**Comment by manojhotmail** [comment]
> I'm facing this issue. Tried all solutions, no luck. Any help would be appreciated.
> 
> ```
> java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
> 
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	at io.restassured.RestAssured.<clinit>(RestAssured.java:347)
> 	at com.bankbazaar.nanoUrlServiceTest.NanoUrlServiceBackwardTest.setup(NanoUrlServiceBackwardTest.java:25)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
> 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
> 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
> 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
> 	at org.testng.TestRunner.beforeRun(TestRunner.java:645)
> 	at org.testng.TestRunner.run(TestRunner.java:613)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
> 	at org.testng.TestNG.run(TestNG.java:1032)
> 	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
> 	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
> Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyObject
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> ```

Try adding this dependency in pom.xml file


		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>3.0.0-beta-1</version>
			<type>pom</type>
		</dependency>

**Comment by MaxMaeder** [comment]
@manojmastiff Hi, I had a similar issue. I tried your proposed solution, but I now get this error:
```
[04:36:06] [Thread-14/WARN]: Exception in thread "Thread-14" 
[04:36:06] [Thread-14/WARN]: java.lang.AbstractMethodError: Receiver class io.restassured.internal.ResponseParserRegistrar does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.
[04:36:06] [Thread-14/WARN]:    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
[04:36:06] [Thread-14/WARN]:    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
[04:36:06] [Thread-14/WARN]:    at io.restassured.internal.ResponseParserRegistrar.<init>(ResponseParserRegistrar.groovy:44)
[04:36:06] [Thread-14/WARN]:    at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1448)
[04:36:06] [Thread-14/WARN]:    at io.restassured.RestAssured.given(RestAssured.java:653)
[04:36:06] [Thread-14/WARN]:    at ratismal.drivebackup.googledrive.GoogleDriveUploader.retrieveNewAccessToken(GoogleDriveUploader.java:205)
[04:36:06] [Thread-14/WARN]:    at ratismal.drivebackup.googledrive.GoogleDriveUploader.<init>(GoogleDriveUploader.java:176)
[04:36:06] [Thread-14/WARN]:    at ratismal.drivebackup.UploadThread.run(UploadThread.java:60)
[04:36:06] [Thread-14/WARN]:    at java.base/java.lang.Thread.run(Thread.java:834)
```

This is the relevant part of my `pom.xml`:
```
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>3.0.0-beta-1</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>4.3.0</version>
        </dependency>
```

Any ideas you might have to why this isn't working would be greatly appreciated!

**Comment by amit-inamdar84** [comment]
In my case I was testing restful webservices using rest assured library. I was using very old versions of dependencies. Just updated my POM.xml with all the latest versions and my test cases ran without any issues. Below is my POM.xml. Hope it helps someone.
<dependencies>
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>4.3.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20200518</version>
		</dependency>

		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.14.3</version>
			<scope>compile</scope>
		</dependency>

		
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.6</version>
		</dependency>

	</dependencies>
