### ISSUE TITLE
EOFException occurs when POST response have an empty body with gzip content type

### ISSUE THREAD

**Issue by anatoly-antonov** [rest-assured/rest-assured#814]
When a POST request returns with empty body and Content-Encoding is equal to gzip, an EOFException exception is thrown. See exception stack trace below:

```java
Caused by: java.io.EOFException
  at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
  at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
  at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
  at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
  at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
  at com.jayway.restassured.internal.http.GZIPEncoding$GZIPDecompressingEntity.getContent(GZIPEncoding.java:66)
  at org.apache.http.conn.BasicManagedEntity.getContent(BasicManagedEntity.java:87)
  at com.jayway.restassured.internal.http.HTTPBuilder.parseResponse(HTTPBuilder.java:544)
  at com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.super$2$parseResponse(RequestSpecificationImpl.groovy)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
  at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
  at com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.parseResponse(RequestSpecificationImpl.groovy:2056)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
  at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
  at com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:1992)
  at com.jayway.restassured.internal.http.HTTPBuilder.post(HTTPBuilder.java:341)


```

**Comment by johanhaleby** [comment]
Thanks for reporting. I've fixed this in master now.

**Comment by sergeytrasko** [comment]
Actually there are cases when server responds with empty body (e.g. with 201 response code) and the response has GZIP encoding (either set by server itself or by some middleware between server and client).
In other words, unknown content length (i.e. wrappedEntity.getContentLength() == -1) can be also in case of empty body.

**Comment by johanhaleby** [comment]
Hmm ok, does it cause any issues?

**Comment by sergeytrasko** [comment]
Yes, it does.
We get getContentLength() == -1 and input stream with content is empty.
Thus creating GZIPInputStream from empty stream results in java.io.EOFException.

I will submit PR later.

**Comment by johanhaleby** [comment]
Great!
