### ISSUE TITLE
Error with processing GZIPPED response

### ISSUE THREAD

**Issue by ninjubohra** [rest-assured/rest-assured#853]
I found an issue in 3.0.3-SNAPSHOT code, this behavior works fine in 3.0.2 version.  I had moved to 3.0.3-SNAPSHOT to while investigating issue #563 and while I was there I noticed the error.

We have two environments (dev and stage), one difference with stage is that we send back the webservice results gzip (compressed)
`14:07:22.143 [Test worker] DEBUG org.apache.http.wire -  << "Vary: Accept-Encoding[\r][\n]"
14:07:22.143 [Test worker] DEBUG org.apache.http.wire -  << "Content-Encoding: gzip[\r][\n]"
14:07:22.143 [Test worker] DEBUG org.apache.http.wire -  << "Transfer-Encoding: chunked[\r][\n]"
`
But with the **3.0.3-SNAPSHOT** version I am getting the following error

`14:07:22.148 [Test worker] DEBUG o.a.h.impl.client.DefaultHttpClient - Connection can be kept alive indefinitely
14:07:22.160 [Test worker] DEBUG i.r.i.RequestSpecificationImpl$RestAssuredHttpBuilder - Parsing response as: application/json;charset=UTF-8
14:07:22.161 [Test worker] DEBUG i.r.i.RequestSpecificationImpl$RestAssuredHttpBuilder - Parsed data to instance of: class org.apache.http.conn.EofSensorInputStream
14:07:22.216 [Test worker] DEBUG org.apache.http.wire -  << "87[\r][\n]"
14:07:22.216 [Test worker] DEBUG org.apache.http.wire -  << "[0x1f][0x8b][0x8][0x0][0x0][0x0][0x0][0x0][0x0][0x3][0xab]V*-N-[0xf2]LQ[0xb2]RJ50176[0xb7]T[0xd2]Q[0xca]II,[0x0][0xb][0xa5][0x19][0xa5][0x98]Z[0x9a][[0x1a][0xe9][0x1a]$[0x99]%[0xea][0x9a][0x18][0x1a][0xa5][0xe9]Z$[0x9b][0x1b][0xea][0xa6][0x19][0x1a][0x1b]'[0x1b]Z[0x98][0xa4]%[0xa7][0x19]+[0xe9]([0xa5]e[0x16][0x15][0x97][0xf8]%[0xe6][0xa6]*Y)[0xf9]e[0xe6]e[0x95][0x82][0xcc]H[0x84][0xb]9[0xe5]g[0x14]%*[0xe9](%[0xe7][0xe7]gg[0xa6][0xfa][0xe5][0x97]d&[0xa7]*Y[0x95][0x14][0x95][0xa6][0xd6][0x2][0x0]%[0xf][0x8f]T[0x0][0x0][0x0]"
14:07:22.217 [Test worker] DEBUG org.apache.http.wire -  << "[\r][\n]"
14:07:22.217 [Test worker] DEBUG org.apache.http.wire -  << "0[\r][\n]"
14:07:22.217 [Test worker] DEBUG org.apache.http.wire -  << "[\r][\n]"
14:07:22.217 [Test worker] DEBUG o.a.h.i.c.BasicClientConnectionManager - Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@5a8ef019
14:07:22.217 [Test worker] DEBUG o.a.h.i.c.BasicClientConnectionManager - Connection can be kept alive indefinitely

Failed to parse the JSON document
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
	at io.restassured.path.json.JsonPath.getString(JsonPath.java:351)
	at com.mastercard.commercial.automation.CommercialLoginHelper.getLdapIdForUserId(CommercialLoginHelper.java:44)
	at com.mastercard.commercial.automation.LoginHelper.getResponseDetails(LoginHelper.java:35)
	at com.mastercard.commercial.automation.LoginHelper.passwordLogin(LoginHelper.java:26)
	at com.mastercard.commercial.reporting20.LoginHelperTest.login(LoginHelperTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 2, while reading '�', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
	... 44 more
`
I have attached a zip with the log out from 3.0.2 against both our evns (dev and stage) which work fine and with 3.0.3-SNAPSHOT against both
[RestAssuredIssue.zip](https://github.com/rest-assured/rest-assured/files/962697/RestAssuredIssue.zip)

**Comment by johanhaleby** [comment]
Could you give me an example of your test case and what your server returns since I can't seem to reproduce this. See [this](https://github.com/rest-assured/rest-assured/blob/master/examples/rest-assured-itest-java/src/test/java/io/restassured/itest/java/GzipITest.java) test for example.

**Comment by ninjubohra** [comment]
In the attached zip file I have an example of the uncompressed JSON (3.0.3-SNAPSHOT_dev_success.txt)
`14:09:05.483 [Test worker] DEBUG i.r.i.RequestSpecificationImpl$RestAssuredHttpBuilder - Parsed data to instance of: class org.apache.http.conn.EofSensorInputStream
14:09:05.543 [Test worker] DEBUG org.apache.http.wire -  << "80[\r][\n]"
14:09:05.543 [Test worker] DEBUG org.apache.http.wire -  << "{"userId":"e047379","ldapId":"0dfdf5a0-483c-45d7-8b24-8dd1299586c8","firstName":"Ninju","lastName":"BohraB","cookieNotice":true}"
14:09:05.544 [Test worker] DEBUG org.apache.http.wire -  << "[\r][\n]"
14:09:05.545 [Test worker] DEBUG org.apache.http.wire -  << "0[\r][\n]"
14:09:05.545 [Test worker] DEBUG org.apache.http.wire -  << "[\r][\n]"
`
And you can see the compressed JSON (3.0.2_stage_success.txt)
`14:12:00.561 [Test worker] DEBUG i.r.i.RequestSpecificationImpl$RestAssuredHttpBuilder - Parsing response as: application/json;charset=UTF-8
14:12:00.561 [Test worker] DEBUG org.apache.http.wire -  << "87[\r][\n]"
14:12:00.562 [Test worker] DEBUG org.apache.http.wire -  << "[0x1f]"
14:12:00.562 [Test worker] DEBUG org.apache.http.wire -  << "[0x8b]"
14:12:00.562 [Test worker] DEBUG org.apache.http.wire -  << "[0x8]"
14:12:00.562 [Test worker] DEBUG org.apache.http.wire -  << "[0x0]"
14:12:00.563 [Test worker] DEBUG org.apache.http.wire -  << "[0x0][0x0][0x0][0x0][0x0][0x3]"
14:12:00.563 [Test worker] DEBUG i.r.i.RequestSpecificationImpl$RestAssuredHttpBuilder - Parsed data to instance of: class org.apache.http.conn.EofSensorInputStream
14:12:00.626 [Test worker] DEBUG org.apache.http.wire -  << "[0xab]V*-N-[0xf2]LQ[0xb2]RJ50176[0xb7]T[0xd2]Q[0xca]II,[0x0][0xb][0xa5][0x19][0xa5][0x98]Z[0x9a][[0x1a][0xe9][0x1a]$[0x99]%[0xea][0x9a][0x18][0x1a][0xa5][0xe9]Z$[0x9b][0x1b][0xea][0xa6][0x19][0x1a][0x1b]'[0x1b]Z[0x98][0xa4]%[0xa7][0x19]+[0xe9]([0xa5]e[0x16][0x15][0x97][0xf8]%[0xe6][0xa6]*Y)[0xf9]e[0xe6]e[0x95][0x82][0xcc]H[0x84][0xb]9[0xe5]g[0x14]%*[0xe9](%[0xe7][0xe7]gg[0xa6][0xfa][0xe5][0x97]d&[0xa7]*Y[0x95][0x14][0x95][0xa6][0xd6][0x2][0x0]%[0xf][0x8f]T[0x0][0x0][0x0]"
14:12:00.627 [Test worker] DEBUG org.apache.http.wire -  << "[\r][\n]"
14:12:00.627 [Test worker] DEBUG org.apache.http.wire -  << "0[\r][\n]"
14:12:00.627 [Test worker] DEBUG org.apache.http.wire -  << "[\r][\n]"
`
The code works fine in 3.0.2 version but fails in 3.0.3-SNAPSHOT

**Comment by johanhaleby** [comment]
It works for me when I GZip compress your data manually:

```json
{"userId":"e047379","ldapId":"0dfdf5a0-483c-45d7-8b24-8dd1299586c8","firstName":"Ninju","lastName":"BohraB","cookieNotice":true}
```

But this is not valid GZIP:

```
[0xab]V*-N-[0xf2]LQ[0xb2]RJ50176[0xb7]T[0xd2]Q[0xca]II,[0x0][0xb][0xa5][0x19][0xa5][0x98]Z[0x9a][[0x1a][0xe9][0x1a]$[0x99]%[0xea][0x9a][0x18][0x1a][0xa5][0xe9]Z$[0x9b][0x1b][0xea][0xa6][0x19][0x1a][0x1b]'[0x1b]Z[0x98][0xa4]%[0xa7][0x19]+[0xe9]([0xa5]e[0x16][0x15][0x97][0xf8]%[0xe6][0xa6]*Y)[0xf9]e[0xe6]e[0x95][0x82][0xcc]H[0x84][0xb]9[0xe5]g[0x14]%*[0xe9](%[0xe7][0xe7]gg[0xa6][0xfa][0xe5][0x97]d&[0xa7]*Y[0x95][0x14][0x95][0xa6][0xd6][0x2][0x0]%[0xf][0x8f]T�[0x0][0x0][0x0]
```

Could you use wireshark and paste the contents from there instead?

**Comment by ninjubohra** [comment]
Hmm...I also noticed that the GZIP response data from the **3.0.2_stage_success.txt** file is different that what is in the **3.0.3-SNAPSHOT_stage_failure.txt**, which is strange because the content should be the same (there are no timestamps or anything like)

I will investigate further...sorry for the bother

**Comment by ninjubohra** [comment]
I don't think you grabbed the _entire_ GZIP response.  The GZIP response is listed/echoed differently in each version of RestAssured 
In **3.0.2_stage_success.txt** (which works) the writing out the GZIP response appears to be split
![image](https://cloud.githubusercontent.com/assets/2438312/25535427/a12cbe26-2bfc-11e7-8327-09f7f690c40a.png)

While in **3.0.3-SNAPSHOT_stage_failure** (which fails) the logging is different
![image](https://cloud.githubusercontent.com/assets/2438312/25535694/a009d8f2-2bfd-11e7-9f2e-874e308284c2.png)

**Comment by johanhaleby** [comment]
And it's the exact same REST Assured test? Would it be possible for you to send me the byte stream that's generated by the server? If you have the REST Assured code in front of you, could you try executing your REST Assured test if you remove [this](https://github.com/rest-assured/rest-assured/blob/a3f34e7cf0b3ffc59b649b5118208cb4553d6b56/rest-assured/src/main/java/io/restassured/internal/http/GZIPEncoding.java#L67) if-statement? I.e. always do `return new GZIPInputStream(content);` (without an if) to see if this is the problem?

**Comment by ninjubohra** [comment]
Yep looks like the second part of the if check is prohibiting the code from running

![image](https://cloud.githubusercontent.com/assets/2438312/25596517/1ee85c50-2e8f-11e7-8239-34cf1b1113c5.png)

If I adjust the value of the contentLength attribute I can get a valid result for the GZIP response

![image](https://cloud.githubusercontent.com/assets/2438312/25596561/52b77354-2e8f-11e7-82ac-eae89975073c.png)

**Comment by johanhaleby** [comment]
Thanks for trying it out again. Interesting, is your server reporting -1 as content-length or is it not sent by the server at all?

**Comment by johanhaleby** [comment]
Anyway, I've added an additional check for "-1" now. Please try version `3.0.3-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by ninjubohra** [comment]
Have you published the newest version OR have been too hasty in my fetch?

I cleared my local gradle cache and it does not look the code has been updated yet

![image](https://cloud.githubusercontent.com/assets/2438312/25623054/e43e84a2-2f1b-11e7-9754-690e53546df6.png)

**Comment by ninjubohra** [comment]
Oops...I accidentally clicked the wrong button

**Comment by johanhaleby** [comment]
Hmm strange, I've tried publishing it again.

**Comment by ninjubohra** [comment]
Had a caching issue of 'snapshot' on our side (at the corporate level).  Once that was cleared I was able to get the latest.

All is well
