### ISSUE TITLE
NoClassDefFoundError: com/github/scribejava/core/model/AbstractRequest

### ISSUE THREAD

**Issue by vbachurin** [rest-assured/rest-assured#883]
compile 'io.rest-assured:rest-assured:3.0.3'
    compile 'com.github.scribejava:scribejava-core:4.1.2'

I have added an OAuth2 authentication into the RestAssured configuration:

    RestAssured.authentication = oauth2(accessToken);

And one of my tests sends the DELETE, where I get the following exception:

    java.lang.NoClassDefFoundError: com/github/scribejava/core/model/AbstractRequest

	at io.restassured.internal.http.AuthConfig.oauth2(AuthConfig.java:188)
	at io.restassured.internal.http.AuthConfig$oauth2.call(Unknown Source)
    ...
	at io.restassured.internal.RequestSpecificationImpl.delete(RequestSpecificationImpl.groovy:180)
	at io.restassured.internal.RequestSpecificationImpl.delete(RequestSpecificationImpl.groovy)
	at io.restassured.RestAssured.delete(RestAssured.java:838)
    ...

Looks like this `AbstractRequest` class was deprecated and last seen in version 4.0.0.

http://static.javadoc.io/com.github.scribejava/scribejava-core/4.0.0/com/github/scribejava/core/model/AbstractRequest.html

**Comment by mkarthik90** [comment]
@vbachurin Any work around for this issue?

**Comment by snpanigrahi9** [comment]
Getting same error with Ouath1.0 also..
How to solve it?

**Comment by TechnoCraftCons** [comment]
You can download the below jars from Maven repository for you oauth authentication



<dependency>
    <groupId>com.github.scribejava</groupId>
    <artifactId>scribejava-apis</artifactId>
    <version>2.5.3</version>
</dependency>

**Comment by kmaterka** [comment]
You need to use older version of scribe:
[Maven search](https://search.maven.org/search?q=g:com.github.scribejava%20fc:com.github.scribejava.core.model.AbstractRequest)
