### ISSUE TITLE
Oath class cast exception in AuthConfig

### ISSUE THREAD

**Issue by kmaterka** [rest-assured/rest-assured#884]
In line 231
`this.service = (OAuth10aService) getOauthService(isOAuth1, addEmptyTokenToBaseString);`
but getOauthService returns OAuthService with incompatible to OAuth10aService implementation: OAuth20Service. This leads to:
```
java.lang.ClassCastException: com.github.scribejava.core.oauth.OAuth20Service cannot be cast to com.github.scribejava.core.oauth.OAuth10aService

	at io.restassured.internal.http.AuthConfig$OAuthSigner.process(AuthConfig.java:231)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
```
Sample execution:
```
given()
        .accept("application/zip")
.when()
        .auth().oauth2(token, QUERY_STRING)
        .get(Urls.pathToTest)
.then().log().all()
```

One note: without QUERY_STRING parameter it is working fine (and does not require com.github.scribejava optional dependency).

**Comment by chucknelson** [comment]
Also experiencing this problem with a slightly different use - simply trying to set default OAuth2 authentication for all requests:

`RestAssured.authentication = RestAssured.oauth2(authToken);`

I receive the same exception as reported by @kmaterka above.

To work around this I just explicitly create the OAuth2 scheme:

```
PreemptiveOAuth2HeaderScheme myScheme = new PreemptiveOAuth2HeaderScheme();
myScheme.setAccessToken(authToken);
RestAssured.authentication = myScheme;
```

Simply calling oauth2(token) should work based on what I see in the docs.

**Comment by johanhaleby** [comment]
@chucknelson Your problem has been addressed in master. Please try version `3.0.4-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by kmaterka** [comment]
Sorry for late response.

I tested 3.0.4-SNAPSHOT and 3.0.7 - both are not working, the same class cast exception. Maybe the fix was reverted?

**Comment by levinzhang1981** [comment]
I encounter the same exception.Is there any suggestion?

**Comment by ksenia-loseva** [comment]
@johanhaleby is this issue still actual? Looks like this one and #883 make make it impossible to use OAuth2 header authorization with AuthenticationScheme.

However, there is AuthFilter that is probably what most of the people use in their tests.
So, should this issue be fixed or abandonned?:

**Comment by kmaterka** [comment]
@ksenia-loseva Issue #883 is not related, it is just missing optional dependency (or it is too new/old) .

Issue discussed here is still there, please check:
[AuthConfig.java L260](https://github.com/rest-assured/rest-assured/blob/master/rest-assured/src/main/java/io/restassured/internal/http/AuthConfig.java#L260)
It casts incompatible classes:
`this.service = (OAuth10aService) getOauthService(isOAuth1, addEmptyTokenToBaseString);`
getOauthService for OAuth2 returns new OAuth20Service(api, oauthConfig):
[AuthConfig.java L328](https://github.com/rest-assured/rest-assured/blob/master/rest-assured/src/main/java/io/restassured/internal/http/AuthConfig.java#L328)

These two are not compatible:
`com.github.scribejava.core.oauth.OAuth10aService`
`com.github.scribejava.core.oauth.OAuth20Service`

There is a common base class that should be used:
`com.github.scribejava.core.oauth.OAuthService`

**Comment by ksenia-loseva** [comment]
@kmaterka I know that these issues are not related. My point was that issue #883 doesn't allow using newer versions of scribe library. However, if you import the older one like 2.5.3, you get this issue with ClassCastException. These two issues completely block using OAuth2Scheme regardless of the version of scribe.
Therefore looks like nobody is using OAuth2Scheme since Rest Assured 3.0.3. Maybe it can be deprecated and deleted then? Or should it be fixed by updating to using the latest version of scribe (and not the one from 2016)?

**Comment by kmaterka** [comment]
@ksenia-loseva Sorry, now I understand your point. Yes, you are right, this feature is unusable for very long time and probably no-one uses it. AFAIR there are workarounds, this method was inconvenient anyway - it required optional dependency which was not obvious.
IMO the best would be to fix this and document well. From the other side if it is not used anymore and there are better ways to set OAuth authentication then it should be deprecated and/or removed.
