### ISSUE TITLE
Multipart content type

### ISSUE THREAD

**Issue by kgk1234** [rest-assured/rest-assured#919]
Hi Everyone,

 I am making a REST call using the RESTAssured library. I have an attachment in the request which I am attaching using "multipart()" method. For my API I should be passing "application/x-abc-xyz+xml" as the Content-Type. When I tried setting this using " contentType()" method I get below error. However preceding the conten-type with "multipart/" will resolve this error but I am not getting the REST response from the server because it expects the content-type without "multipart/" prefix. I need help in resolving this issue. Any help would be appreciated. Thanks!

java.lang.IllegalArgumentException: **Content-Type application/x-abc-xyz+xml is not valid when using multiparts, it must start with "multipart/".**
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
  at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
  at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
  at io.restassured.internal.RequestSpecificationImpl.registerRestAssuredEncoders

**Comment by johanhaleby** [comment]
I think I've fixed this in master now, and I've published a new snapshot. Please try version `3.0.4-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by kgk1234** [comment]
Thanks johanhaleby for making the changes. I am able to send any content-type and I do not see below exception now.
**java.lang.IllegalArgumentException:** Content-Type application/x-abc-xyz+xml is not valid when using multiparts, it must start with "multipart/".


However the API execution is failing.  The API I am testing performs the file validation before uploading the file and the validation is always failing. I was trying to make changes to the file thinking the file I am uploading has problem but the same request with the same multipart file is succeeding in ReadySPI/SOAPUI tool. I think the problem is not with the request.

I am not able to figure out the exact issue here. I noticed few changes in the way multipart is getting sent in the request after using "3.0.4-SNAPSHOT" branch.  I see extra hyphens and "content=" is missing. Will these have an impact in file validation? Sorry for the later reply. I was trying to debug this issue. 

**Earlier:**
Multiparts:		controlName=file, mimeType=application/octet-stream, charset=<none>, fileName=yy.txt, **content**=C:\abc\uploadFile.txt

**After using 3.0.4-SNAPSHOT version:**
Multiparts:		**------------**
				Content-Disposition: application/x-hub-multipart+xml; name = file; filename = yy.txt
				Content-Type: application/octet-stream
				C:\abc\uploadFile.txt

**Comment by johanhaleby** [comment]
Hmm and the only thing you change is the content-type?

**Comment by kgk1234** [comment]
I need to assign Content-Type with the value  "application/x-abc-xyz+xml" and attach a file in the request.

**Comment by johanhaleby** [comment]
I don't think that works in the current version.

**Comment by johanhaleby** [comment]
If it's possible for you to add `+multipart` to the content-type then maybe that could be a workaround?

**Comment by kgk1234** [comment]
Unfortunately I cannot change the content-type because it is being used by several teams and it is already in the production.  When I add "multipart/" prefix I get "Unsupported Media Type" error message. 

Adding +multipart suffix gives below exception.
java.lang.IllegalArgumentException: Content-Type application/x-abc-xyz+xml+multipart is not valid when using multiparts, it must start with "multipart/".

**Comment by kgk1234** [comment]
I believe my issue will get resolved if we remove below restriction. 
when using multiparts, content-type must start with "multipart/".

**Comment by johanhaleby** [comment]
Yeah, I don't remember off the top of my head why I added "multipart/". Maybe it had something to do with adding of automatic charset and that this should be avoided for multiparts. Maybe there's another (better) way to do it.

**Comment by kgk1234** [comment]
Can you please reopen this thread? I see it is in closed status now.

**Comment by johanhaleby** [comment]
Sure, sorry

**Comment by kgk1234** [comment]
Thank you!

**Comment by kishgary** [comment]
Hi Johanhaleby/ kgk1234,

I have the same problem. Can you please respond with answer if this is resolved?

Thanks

**Comment by realnikunj** [comment]
Hi @johanhaleby ,

I am running into the same issue now,is this resolved in some version of RestAssured ?

Thanks!

**Comment by Reshma-cb** [comment]
Hi @johanhaleby ,
Do we have a solution to this? I am stuck with this issue :(

**Comment by amoltambe87** [comment]
Hi @Reshma-cb,
I was facing same issue and it turned out to be not a multipart upload but through body.
Please do not mention the header explicitly as "application/octet-stream".
I was able to solve it and got it working successfully with simple code ,
`given().
header("Content-Type","text/csv").
headers("Authorization","bla-blah","Header 2","blahblah").
body(new File("your-file-[ath")).
when().
post("/post-url");
`
