### ISSUE TITLE
Can not do GET request for the link which has redirect link with symbols

### ISSUE THREAD

**Issue by KseniaBudlianska** [rest-assured/rest-assured#927]
I'm doing get request to the link which is doing a lot of redirects. And basically I need them all and I can't add the next line: .redirects().follow(false)

So, I'm raising the issue, could someone fix situation when there is some symbols in redirect urls. Please view the stack trace below or let me now if you need anything else.

org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:839)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:2128)
	at io.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:494)
	at io.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:451)
	at io.restassured.internal.http.HTTPBuilder$request$2.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1531)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
	at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)
	at io.restassured.filter.Filter$filter$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at io.restassured.filter.Filter$filter.call(Unknown Source)
	at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
	at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)
	at io.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at io.restassured.filter.Filter$filter.call(Unknown Source)
	at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
	at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:124)
	at io.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at io.restassured.filter.Filter$filter$0.call(Unknown Source)
	at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
	at io.restassured.filter.FilterContext$next.call(Unknown Source)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1731)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
	at api.bulkapiv2.JsonBulkApiV2ClickTests.lambda$null$1(JsonBulkApiV2ClickTests.java:118)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at api.bulkapiv2.JsonBulkApiV2ClickTests.lambda$getOfferWithCorrectUrl$2(JsonBulkApiV2ClickTests.java:111)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1249)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at api.bulkapiv2.JsonBulkApiV2ClickTests.getOfferWithCorrectUrl(JsonBulkApiV2ClickTests.java:122)
	at api.bulkapiv2.JsonBulkApiV2ClickTests.affSubParametersAndCountryTest(JsonBulkApiV2ClickTests.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: org.apache.http.ProtocolException: Invalid redirect URI: https://app.adjust.com/n93roy?campaign=CB__^COJ^xdm531^^^&adgroup=25810&gps_adid=&creative=&install_callback=http%3A%2F%2Ftracking.applift.com%2Faff_lsr%3Ftransaction_id%3D102d8983274396d22debf17fc13d3f%26adv_sub2%3D%7Binstalled_at%7D%26adv_sub3%3D%7Blanguage%7D%26adv_sub%3D%7Bgps_adid%7D&event_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D102d8983274396d22debf17fc13d3f%26event_ref_id%3D%7Bevent%7D%26event_name%3D%7Bevent_name%7D%26event_value%3D%7Brevenue_usd%7D&session_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D102d8983274396d22debf17fc13d3f%26event_ref_id%3Dsession&rejected_install_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D%7Btransaction_id%7D%26custom10%3Drejected_%7Brejection_reason%7D%26custom9%3D25810%26custom8%3D46088%26post%3D1
	at org.apache.http.impl.client.DefaultRedirectStrategy.createLocationURI(DefaultRedirectStrategy.java:200)
	at org.apache.http.impl.client.DefaultRedirectStrategy.getLocationURI(DefaultRedirectStrategy.java:148)
	at org.apache.http.impl.client.DefaultRedirectStrategy.getRedirect(DefaultRedirectStrategy.java:221)
	at org.apache.http.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:1083)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:514)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	... 126 more
Caused by: java.net.URISyntaxException: Illegal character in query at index 43: https://app.adjust.com/n93roy?campaign=CB__^COJ^xdm531^^^&adgroup=25810&gps_adid=&creative=&install_callback=http%3A%2F%2Ftracking.applift.com%2Faff_lsr%3Ftransaction_id%3D102d8983274396d22debf17fc13d3f%26adv_sub2%3D%7Binstalled_at%7D%26adv_sub3%3D%7Blanguage%7D%26adv_sub%3D%7Bgps_adid%7D&event_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D102d8983274396d22debf17fc13d3f%26event_ref_id%3D%7Bevent%7D%26event_name%3D%7Bevent_name%7D%26event_value%3D%7Brevenue_usd%7D&session_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D102d8983274396d22debf17fc13d3f%26event_ref_id%3Dsession&rejected_install_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D%7Btransaction_id%7D%26custom10%3Drejected_%7Brejection_reason%7D%26custom9%3D25810%26custom8%3D46088%26post%3D1
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.http.impl.client.DefaultRedirectStrategy.createLocationURI(DefaultRedirectStrategy.java:189)
	... 131 more

**Comment by johanhaleby** [comment]
Hmm which symbol is it complaining about?

**Comment by KseniaBudlianska** [comment]
@johanhaleby 

Basically I found two links:

1. Complaining {deviceInfo}

Caused by: org.apache.http.ProtocolException: Invalid redirect URI: https://atracking-auto.appflood.com/transaction/post_click?offer_id=24898774&aff_id=10729&aff_sub=201710192144432608733&aff_sub3={deviceInfo}&aff_sub6=10065
2. Complaining due to ^ symbol

Caused by: java.net.URISyntaxException: Illegal character in query at index 43: https://app.adjust.com/n93roy?campaign=CB__^COJ^xdm531^^^&adgroup=25810&gps_adid=&creative=&install_callback=http%3A%2F%2Ftracking.applift.com%2Faff_lsr%3Ftransaction_id%3D102d8983274396d22debf17fc13d3f%26adv_sub2%3D%7Binstalled_at%7D%26adv_sub3%3D%7Blanguage%7D%26adv_sub%3D%7Bgps_adid%7D&event_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D102d8983274396d22debf17fc13d3f%26event_ref_id%3D%7Bevent%7D%26event_name%3D%7Bevent_name%7D%26event_value%3D%7Brevenue_usd%7D&session_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D102d8983274396d22debf17fc13d3f%26event_ref_id%3Dsession&rejected_install_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D%7Btransaction_id%7D%26custom10%3Drejected_%7Brejection_reason%7D%26custom9%3D25810%26custom8%3D46088%26post%3D1

**Comment by johanhaleby** [comment]
Maybe you need to URL Encode it? This looks like something that is thrown by Apache HTTP Client and thus I assume that it's correct. Maybe you could search for issues or ask questions in the Apache HTTP Client mailing list (or stackoverflow or something). If there's anything that can be done about it maybe we can sort something out on the RA side.

**Comment by KseniaBudlianska** [comment]
@johanhaleby Thank you, I will look on this deeply and report to responsible side.
