### ISSUE TITLE
Getting GC Error on Performance and Load testing with Rest-Assured.

### ISSUE THREAD

**Issue by dreamsivaraj** [rest-assured/rest-assured#945]
Hi,

I have tried to use Rest-Assured for component and functional testing of our SOA Services. Its working good. When I try to do performance testing for specific API. ( Made multiple threads to make http requests using Rest-Assured. RequestSpecificationObject.post(....). But getting GC Error after 5 mins of execution.

failed: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at ESC[3;31m******************************************************************************************ESC[3;0m.(:0)
        at ESC[3;31m******************************************************************************************ESC[3;0m.(:0)
        at ESC[3;31m* This error was thrown from your transaction code.                                       ESC[3;0m.(:0)
        at ESC[3;31m* Please attempt to debug it before contacting the TPSGenerator team.                     ESC[3;0m.(:0)
        at ESC[3;31m******************************************************************************************ESC[3;0m.(:0)
        at ESC[3;31m******************************************************************************************ESC[3;0m.(:0)
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at org.codehaus.groovy.runtime.StringGroovyMethods.plus(StringGroovyMethods.java:2358)
        at org.codehaus.groovy.runtime.dgm$1122.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at io.restassured.internal.RequestSpecificationImpl.defineRequestContentType(RequestSpecificationImpl.groovy:1510)
        at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
        at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)

When I gone through the thread - https://groups.google.com/forum/#!topic/rest-assured/-GNquxD2Zes it is specified that its not thread safe.

Please clarify is Rest-Assured thread safe and suitable for performance testing ?

**Comment by RocketRaccoon** [comment]
Hi,

It is not thread safe, but if you don't rely on default properties in tests it won't be a real issue. Some day it will be thread safe, I hope :)

Any way, it is not design for real perfomance testing, it's main point provide flexible DSL and bring power of Groovy for responses parsing and verification. But Groovy provides overhead in memory usage with all it's meta data, it will take all available memory very fast. And yeah, there is an issue with garbage collecting all that staff.

So, for perfomance testing it would be better to use someting like [gatling](https://gatling.io/).
