### ISSUE TITLE
graphql testing

### ISSUE THREAD

**Issue by mrcasablr** [rest-assured/rest-assured#958]
Wondering if there is graphql support planned.  This tool is incredible and as we move from rest to graphql, would love for graphql to be supported

**Comment by johanhaleby** [comment]
There are no plans for that. But contributions are welcome :)

**Comment by ksiv** [comment]
@mrcasablr , could you elaborate further. What is your issues with graphql?
graphql response is plain JSON and works out of the box all you need is to put your json request into requst body with about same amount of efforts as you do your params for REST request.

**Comment by ansonliao** [comment]
@ksiv 
Could you provide a sample that rest-assured send graphql query to the backend, 

for exmple, 

URL: https://graphqlserver.com/graphql/v1
Headers: key = `apikey`, value = `zzzzzzzz`
Query String = 
```graphql
{
  user(filter: {entityId: "2164686"}) {
     id
  }
}
```

My code in `rest-assured` as below, and 

```java
public static void main(String[] args) {
        String url = "https://graphqlserver.com/graphql/v1;
        String headerKey = "apikey";
        String headerValue = "zzzzzzzz";

        String payload = "{\n" +
                "  user(filter: {entityId: \"2164686\"}) {\n" +
                "    id\n" 
                "  }\n" +
                "}";
        Map<String, String> b = new HashMap<>();
        b.put("query", payload);

        given()
                .contentType(TEXT)
                .header(headerKey, headerValue)
                .body(payload)
                .post(url)
                .then()
                .statusCode(200);
```

always got response code `500` from server, and this sample I migrated to Python is works well.

Please advise.

**Comment by himgupta13** [comment]
Guys, is there any update on this? Do we support graphql API on rest assured?
I want to test Graphql API response through rest assured. 

```
URL: https://xyz/graphql/v1
Headers: content-type = application/graphql
Query String =
query { applyCoupon(fareKey: "DEL-BOM-AI887", providerId: 196, originalAmount: 2243, currency: "INR", isInternational: false, searchToken: "1q4h30lhdtpkdnhhdhphphqhh96ohdddptpduddvsvnwpk", numOfTravellers: 1, couponCode: "MONEY", otherSpend: 0) {coupon {data {couponCode message cashback {amount currency} instantDiscount {amount currency}} error {code message}} burn {data {burnAmount burnRule totalWalletBalance ixigoConvenienceFee} error {code message}}}}
```

On execution, getting below error:

```
java.lang.IllegalArgumentException: Don't know how to encode query { applyCoupon(fareKey: "DEL-BOM-AI887", providerId: 196, originalAmount: 2243, currency: "INR", isInternational: false, searchToken: "1q4h30lhdtpkdnhhdhphphqhh96ohdddptpduddvsvnwpk", numOfTravellers: 1, couponCode: "MONEY", otherSpend: 0) {coupon {data {couponCode message cashback {amount currency} instantDiscount {amount currency}} error {code message}} burn {data {burnAmount burnRule totalWalletBalance ixigoConvenienceFee} error {code message}}}} as a byte stream.

Please use EncoderConfig (EncoderConfig#encodeContentTypeAs) to specify how to serialize data for this content-type.
For example: "given().config(RestAssured.config().encoderConfig(encoderConfig().encodeContentTypeAs("application/graphql", ContentType.TEXT))). .."

	at com.jayway.restassured.internal.http.EncoderRegistry.encodeStream(EncoderRegistry.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1077)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at com.jayway.restassured.internal.http.HTTPBuilder$RequestConfigDelegate.setBody(HTTPBuilder.java:1088)
	at com.jayway.restassured.internal.http.HTTPBuilder$RequestConfigDelegate.setPropertiesFromMap(HTTPBuilder.java:1002)
	at com.jayway.restassured.internal.http.HTTPBuilder.post(HTTPBuilder.java:336)
	at com.jayway.restassured.internal.http.HTTPBuilder$post$2.call(Unknown Source)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
	at com.jayway.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)
	at com.jayway.restassured.filter.Filter$filter$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:73)
	at com.jayway.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:73)
	at com.jayway.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:101)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at com.jayway.restassured.filter.Filter$filter$0.call(Unknown Source)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:73)
	at com.jayway.restassured.filter.FilterContext$next.call(Unknown Source)
	at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1596)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.jayway.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:164)
	at com.jayway.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
	at com.ixigo.apiframework.BaseTest.executeApi(BaseTest.java:424)
	at com.ixigo.apiframework.BaseTest.getApiResponse(BaseTest.java:295)
	at com.ixigo.apiframework.BaseTest.executeTestCase(BaseTest.java:524)
	at com.ixigo.apiframework.Flights.graphTest.graphApiValidation(graphTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

Please advise how to solve this?

**Comment by nicodn** [comment]
@himgupta13 has probably already figured this out but for those who come after, the answer is in the stacktrace itself:

`given().config(RestAssured.config().encoderConfig(encoderConfig().encodeContentTypeAs("application/graphql", ContentType.TEXT))).`

That solved it for me!

**Comment by ksiv** [comment]
> Please advise.
18 yr in IT, took a break :-) Sorry could not answer and you most likely not need any advice at the time.
Still best advice here to set up a debug proxy server like a fiddler and check what you sending. If you have a working example on other sdk you just check what is sent by debug-proxy and fix it in java to match.

**Comment by JakimLi** [comment]
@nicodn applied you approach, but it seems still using json parser to parse the graphql query text.

**Comment by kurf16** [comment]
@nicodn  I have the same in the my rest assured request 
`given().config(RestAssured.config().encoderConfig(encoderConfig().encodeContentTypeAs("application/graphql", ContentType.TEXT))).`  but I am getting 400 Bad request

**Comment by ksiv** [comment]
> @ksiv
> Could you provide a sample that rest-assured send graphql query to the backend,

Sorry took me so long (I m getting a rest from IT activity), you definitely do not need it by now. But maybe it will help someone else.

`/**
 * Simple example of a request to http://graphql.nodaljs.com/
 * please do no abuse this service, this one of a first working endpoint I v found :-)
 */
import io.restassured.RestAssured;
import  static  org.hamcrest.Matchers.*;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import org.junit.Test;

public class sample1 {

    @Test
    public void makeSureThatGoogleIsUp() {
        String reqString = "user(username: \"Sansa Stark\") {\n" +
                "  id,\n" +
                "  username,\n" +
                "\n" +
                "\n" +
                "}";
        RequestSpecification request = RestAssured.given();
        request.header("Content-Type", "application/json");
        request.body(reqString);
        Response response = request.post("http://graphql.nodaljs.com/graph");
        response.then().body("data.id[0]".toString(), equalTo(3));
    }

}`

**Comment by tlqiao** [comment]
@ksiv,hi,ksiv, I meet same issue"rest-assured can't call graphql api".
it seems that your demo api is not real graphql api, because I can't call above demo api with graphql type in postman. details is below.
![image](https://user-images.githubusercontent.com/16421412/70704696-83b9e580-1d0d-11ea-8b22-9f8246c1bde1.png)
Here is my tested graphql api, I can call it with postman as below.
![image](https://user-images.githubusercontent.com/16421412/70705103-5a4d8980-1d0e-11ea-9f1d-82134945d782.png)
but I can't call it with rest-assured.below it my code and error details.
import spock.lang.Specification
import static io.restassured.RestAssured.given

class CallGraphqlAPIDemo extends Specification {


    def "this is a demo for calling graphql api"() {
        given: "no given"
        String body = "{bookById (id: \"book-1\") {\n" +
                "\tid\n" +
                "\tname\n" +
                "\tpageCount\n" +
                "\tauthor{\n" +
                "\t\tfirstName\n" +
                "\t\tlastName\n" +
                "\t}\n" +
                "}\n" +
                "}"
        when: "call the api"
        def res = given()
                .contentType("application/json")
                .baseUri("http://localhost:8080/graphql").log().all()
                .body(body)
                .post()
                .then().log().all().assertThat().statusCode(200)
                .extract().response().getBody().toString()

        then: "println response"
        println res
    }
}

Error Details
  "status": 400,
    "error": "Bad Request",
    "message": "JSON parse error: Unexpected character ('b' (code 98)):
you can find the tested api from here: https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/

**Comment by britka** [comment]
Hello all. 
I tried to make call to shared GrahpQL service:
```
 @Test
    public void graphQLTest() {
        given()
                .body("{\n" +
                        "    \"query\": \"{ product(id: \\\"UHJvZHVjdDo3NA==\\\"){ name  description  category { name  id } images{ id alt url}}}\" \n" +
                        "}")
                .post("https://demo.getsaleor.com/graphql/")
                .prettyPeek();
    }
```
And I've got the results:
```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 408
Connection: keep-alive
Date: Thu, 12 Dec 2019 12:51:32 GMT
Server: nginx/1.12.1
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Headers: Origin, Content-Type, Accept, Authorization
Vary: Accept-Language, Cookie
Content-Language: en
X-Cache: Miss from cloudfront
Via: 1.1 275c261effb3ee5f39bd3dd96f438f26.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SFO5-C3
X-Amz-Cf-Id: C9JGFp5_suknabWC4WcB3XHeksqWfkDVOultiHq9YHmIMEQrA-iKew==

{
    "data": {
        "product": {
            "name": "Banana Juice",
            "description": "Build your protein the natural way, with exotic banana juice made from ripe fruit and packed with all the goodness of the tropical sun.",
            "category": {
                "name": "Juices",
                "id": "Q2F0ZWdvcnk6MTQ="
            },
            "images": [
                {
                    "id": "UHJvZHVjdEltYWdlOjUzNzI=",
                    "alt": "",
                    "url": "https://saleor-demo.s3.amazonaws.com/products/saleordemoproduct_fd_juice_01.png"
                }
            ]
        }
    }
}

```

So all works fine. 

From Postman:
![image](https://user-images.githubusercontent.com/2699826/70714092-16e42280-1cf0-11ea-86fe-eb3d0851de98.png)

Also works fine.
So I do not see any issues.

**Comment by ansonliao** [comment]
@britka 
Postman supports GraphQL now, though in beta in the current phase.

**Comment by britka** [comment]
@ansonliao To my mind we are not about Postman. We are about Rest-assured.
I gave example in my previous post about RA. I could call graphQL endpoint just using post() method of RA and well-formed body. That's all.

**Comment by ansonliao** [comment]
@britka 
Yes, Rest-assured can call the GraphQL by `POST` method

**Comment by ansonliao** [comment]
@britka 

My snippet code that `rest-assured` calls the GraphQL as below:

```java
String response = given()
                .contentType(JSON)
                .accept(JSON)
                .header("Authorization", "token")
                .body(payload)
                .post(endpoint).asString();
```

the payload I store as a template file of `jtwig`, sample as below:
```
{
    "query": "{
        article(filter:{entityId: \"{{ articleId }}\"}) {
            entityId,
            entityUuid,
            headline,
            subHeadline,
            socialHeadline,
            sourceUrl,
            urlAlias,
            summary,
            keywords,
            updatedDate,
            publishedDate,
            sections {
                entityId,
                name,
                urlAlias
            },
            authors{
                entityId,
                name
            }
        }
    }",
    "variables": {}
}
```
read the `jtwig` template file and then replace the parameter in need and then convert it to `String` as `payload` of `rest-assured`, finally pass the `rest-assured` http request.

**Comment by tlqiao** [comment]
@ksiv ，thanks ksiv，I resolved my problem.

**Comment by sourabhdargar** [comment]
How to pass Bearer token for authentication, i tried  using:
Response actual = RestAssured.given()
				.header(new Header("Content-type", "application/json")).header("Authorization","Bearer eyJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCI6Nzc4LCJkZXNpZ25hdGlvbklkIjo5LCJkYk5hbWUiOiJzdGFnaW5nZWFsLWV4bF9iaXpvbV9pbl9iaXpvbSIsImlzcyI6IkJpem9tIiwiY2xhc3NpY2V4cCI6MTU3OTA3MTQ4NjIyMywiZXhwIjoxNTc2NTY1ODg4NTgyLCJ1c2VySWQiOjEsImRvbWFpblVybCI6InN0YWdpbmdlYWwtZXhsIiwiY2xhc3NpY1Rva2VuIjoiYjIzZTY1ZTcwODE3MWZjNjc2MjZlYjc2MTA4NTFjNzExZDUwNTI3MCJ9.iBUJs3iGPbAg5VE34rysv-a05zpQjqJpWvvQtjoPr2Y")
but it giver 400 error always

**Comment by ronwald** [comment]
> Hello all.
> I tried to make call to shared GrahpQL service:
> 
> ```
>  @Test
>     public void graphQLTest() {
>         given()
>                 .body("{\n" +
>                         "    \"query\": \"{ product(id: \\\"UHJvZHVjdDo3NA==\\\"){ name  description  category { name  id } images{ id alt url}}}\" \n" +
>                         "}")
>                 .post("https://demo.getsaleor.com/graphql/")
>                 .prettyPeek();
>     }
> ```
> 
> And I've got the results:
> 
> ```
> HTTP/1.1 200 OK
> Content-Type: application/json
> Content-Length: 408
> Connection: keep-alive
> Date: Thu, 12 Dec 2019 12:51:32 GMT
> Server: nginx/1.12.1
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Methods: POST, OPTIONS
> Access-Control-Allow-Headers: Origin, Content-Type, Accept, Authorization
> Vary: Accept-Language, Cookie
> Content-Language: en
> X-Cache: Miss from cloudfront
> Via: 1.1 275c261effb3ee5f39bd3dd96f438f26.cloudfront.net (CloudFront)
> X-Amz-Cf-Pop: SFO5-C3
> X-Amz-Cf-Id: C9JGFp5_suknabWC4WcB3XHeksqWfkDVOultiHq9YHmIMEQrA-iKew==
> 
> {
>     "data": {
>         "product": {
>             "name": "Banana Juice",
>             "description": "Build your protein the natural way, with exotic banana juice made from ripe fruit and packed with all the goodness of the tropical sun.",
>             "category": {
>                 "name": "Juices",
>                 "id": "Q2F0ZWdvcnk6MTQ="
>             },
>             "images": [
>                 {
>                     "id": "UHJvZHVjdEltYWdlOjUzNzI=",
>                     "alt": "",
>                     "url": "https://saleor-demo.s3.amazonaws.com/products/saleordemoproduct_fd_juice_01.png"
>                 }
>             ]
>         }
>     }
> }
> ```
> 
> So all works fine.
> 
> From Postman:
> ![image](https://user-images.githubusercontent.com/2699826/70714092-16e42280-1cf0-11ea-86fe-eb3d0851de98.png)
> 
> Also works fine.
> So I do not see any issues.

![image](https://user-images.githubusercontent.com/48977986/72120394-d03b2400-3392-11ea-8786-4f2ded308cd4.png)

I tried the exact same test, but Im getting error

**Comment by iPiyushPatel** [comment]
Hi,
I'm also facing similar issue i.e. can't get graphql working with RestAssured, it works with postman. Snaps below :

**With RestAssured:**
![image](https://user-images.githubusercontent.com/5212585/75339671-fa9b5f00-58b6-11ea-8911-416f34210194.png)

**With Postman:
![**image](https://user-images.githubusercontent.com/5212585/75339704-0c7d0200-58b7-11ea-8548-7741defc9bd0.png)

Any help would be much appreciated. 

Thanks

**Comment by cport93** [comment]
Hi, after searching and searching, i found this quickly solution:

Graphql String:
```
String value="query{\n" +
--
  | " viewer {\n" +
  | " email,\n" +
  | " }\n" +
  | "}\n";
  | return value;
```

Then use a method to convert to Json:
```
private static String graphqlToJson(String payload){
        JSONObject json = new JSONObject();
        json.put("query",payload);
        return  json.toString();
    }
```

Now you can use your body request as always:

```
String jsonStringResponse= given()
                .header(new Header("Content-type", "application/json"))
                .header("yourheader","value-header")
                .baseUri(YOUR-PATH).log().all()
                .body(requestjson)
                .post().asString();

```

**Comment by vbinsfeld** [comment]
Hi all, I was able to make it work.

So I've been strugling for a while trying to make this graphQL request with Restassured in order to validate the response (amazing how scarce is the info about this) and since this was one of the most helpful forum and yesterday I was able to make it work, thought sharing here might help someone else.

**What was wrong?** By purely copying and pasting my Graphql request (that is not json format) on the request was not working. I kept getting error "Unexpected token t in JSON at position". So I thought it was because graphql is not JSON or some validation of restassured. That said I tried to convert the request to JSON, imported library and lot of other things but none of them worked.

My grahql query request:

        String reqString = "{ trade  { orders { ticker } }}\n";

**How did I fixed it?** By using postman to format my request. Yes, I just pasted on the QUERY window of postman and then clicked on code button on the right side (fig. 1). That allowed my to see my request on a different formatt, a formatt that works on restassured (fig. 2).

My grahql query request FORMATTED:

        String reqString = {"query":"{ trade  { orders { ticker } }}\r\n","variables":{}}

Fig 1.

![image](https://user-images.githubusercontent.com/32341439/78296808-c4c84680-7504-11ea-8262-779bff4d1b9d.png)

Fig 2.

![image](https://user-images.githubusercontent.com/32341439/78296865-e1647e80-7504-11ea-83b6-f792a1efdda4.png)

Hope it helps you out, take care!

**Comment by SteveGecu** [comment]
Can you please share your RestAssured request

**Comment by ksiv** [comment]
it's already been shared by  many people, but it's hard to get where is the issue from other's people code.

grathGQ is a variation of json-RPC with an sorrowful parsing abilities. It does not wish to recognize any valid json but their twisted version. They did it especially to pretend they aren't one in the list but super-duper new thing. In theory they wanna provide some more abilities, but it's several years passed and they still run all payload as plain json. 

For workaround all you need to do is 
1. install transparent proxy.
2. Run postamn request via this proxy
3. run SAME request via restassured as json payload 
4. compare http requests in your proxy app 

after this you ll see where you need add some backslashes or quotes for  grathQL server to finally recognize your "json" request. It is that bad - yes. 

It's three years since this topic started and it seems many people do not wanna format their own JSON for stupid graphQL to recognize it. Maybe it's time to resurrect the original question. 

 **if there is graphql support planned**
 
As I get it what people want is a function (at lest ) to format a json request. into "grathQL-json".
Three years ago there were no plans to implement it :-)

@johanhaleby has anything changed ?

**Comment by Ms-bubble-2** [comment]
Thanks alot for all your valuable Feedback. Just completed the Automation of GraphQL.

CHEERS !

**Comment by ksiv** [comment]
Okay, guys I'm back to IT at least for a while.
I did some more analysis on your posts, and here some thoughts
1. Good % of people try to send GraphQL language inside the query as a body - this is wrong. At the moment most engines uses JSON to communicate and this is why  we can use RESTAssured. For us in API test Grathql is typical JSON-PRC. Testing it in RESTAssured we do not even know this is GraphQL on the upper layer. We just send and receive JSONs.
• If you do not have a snoop proxy you can see browser development tools or Postman. (like suggested by @vbinsfeld )
• if you are not sure if your JSON is good - use online JSON lint tools.
• Use free lightweight server to see https://graphql.org/graphql-js/running-an-express-graphql-server/ which query is turned into which JSON for sending.

2. Suggestion (by @ansonliao ) to use Jtwig - this is quite working solution in-spite the Jtwig is about to die you can use other template engine. But the principal is same you store a piece of correct JSON that represent the query and substitute some markers in it with your data before sending.
 3. Suggestion (by @cport93 ) to use org.json.JSONObject. this will work and I used it, but you need to modify it sometime adding separate fields for "variables" and "operationName"
`    public void setQuery(String query){
        json.put("query",query); //here you put text from query
    }
    public void setVariables(String variables){
        json.put("variables",variables); // here you put text from variables
    }`
Here I made a picture with two cases which call same function but in different but valid syntax.
I personally not sure if it's  worth to implement anything in RESTAssured itself. This post is to clarify and maybe fix some statement from my previous posts. 
4. If you guys have not found an answer maybe re-phrase your question
6. @johanhaleby , Thanks a lot! Great product!

![graptQL](https://user-images.githubusercontent.com/6458864/92303082-5b000d00-ef7a-11ea-9511-c58ec42eee8b.jpg)
