### ISSUE TITLE
Receving a 404 when using Ra,but works fine with postman

### ISSUE THREAD

**Issue by feinier** [rest-assured/rest-assured#995]
This is my code:
@Before
public void before(){
    RestAssured.baseURI="http://"+ip+":"+port+contextPath+"/service/rs";
    RestAssured.port=Integer.parseInt(port);
    RestAssuredMockMvc.webAppContextSetup(context);

}

@Test
public void testAuthService(){
    UPCert upCertS = new UPCert();
    upCertS.setUsername("admin");
    upCertS.setPassword("0c1b4286a7735a85fb022137b7ca27e8225b1343ce4bee22a6bbb848faf6a201");
    given().contentType("application/json").body(upCertS).log().all()
            .when().post( RestAssured.baseURI+"/authcService/v1/authenticateByUsernamePassword")
            .then().statusCode(200);
}

The result:
java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RoccoRaj** [comment]
Remove the RestAssured.baseURI from post method and try it this way
when().post( "/authcService/v1/authenticateByUsernamePassword")
